### ISSUE TITLE
Allow the storage backend implementation to be configurable

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#5495] opened 2022-04-23 19:28 UTC
For now this is hardcoded to the `psql_dos` implementation, however, it would be nice to allow other plugins to provide their own implementation. We could add the `aiida.storage` entry point group which could provide an implementation for `aiida.orm.implementation.storage_backend.StorageBackend`. The profile configuration already defines the storage class to use, we would just have to update the manager code to load the class through the entry point as opposed to the current hardcoded class mapping.

**Comment by chrisjsewell** [comment] 2022-05-04 12:02
this is a duplicate of #5353

**Closed** 2022-05-16 12:54 UTC
Labels: type/accepted feature, priority/nice-to-have, topic/storage
