### ISSUE TITLE
PSQL role used by AiiDA requires LOGIN option

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida-core#617] opened 2017-06-29 12:32 UTC
The documentation tells to create a postgres role with command:

`create role aiida with password 'thepassword'`

assuming that this allows to login to postgres with the credentials of  user aiida.
In some cases, this is not sufficient and one has to make the login option explicit:

`create role aiida with login with password 'the password'`

or, if the role has been already created, add the login options: 

`alter role aiida with login;`

Not being able to login will make `verdi setup` raises the error:

`django.db.utils.OperationalError: FATAL:  role "aiida" is not permitted to log in`

Found together with @fernandogargiulo1986

**Comment by ltalirz** [comment] 2017-10-09 17:04
To be fixed both in the documentation and, possibly, in `quicksetup`

**Comment by sphuber** [comment] 2019-03-15 13:39
> In some cases, this is not sufficient and one has to make the login option explicit:

Do we know in which cases exactly this is the case? I.e. can we reproduce this?

**Comment by ltalirz** [comment] 2019-05-15 20:59
@borellim do you recall which operating system this was on?
This hasn't been part of the documentation for a long time and I haven't heard any other complaints https://aiida-core.readthedocs.io/en/latest/install/installation.html#aiida-profile-setup

**Comment by borellim** [comment] 2019-05-15 21:19
I suppose this was Ubuntu 16.04, since that's the only system I have worked on with AiiDA.
I'm afraid I don't remember any other circumstances about this report, sorry.

**Comment by ltalirz** [comment] 2020-04-06 08:27
Alright, I've looked into this now: it [turns out](https://www.postgresql.org/docs/current/sql-createrole.html) that `LOGIN` is the default, if you use `CREATE USER`, while `NOLOGIN` is the default, if you use `CREATE ROLE`.

As of today, "CREATE ROLE" has no hits in the entire AiiDA codebase.
I thought about whether we need to add an extra mention of this (*not* to use `CREATE ROLE`) but I think in the end it would be more confusing than helpful.

Closing.

**Closed by ltalirz** 2020-04-06 08:27 UTC
Labels: coding-day/wip, topic/documentation
