### ISSUE TITLE
identity between node objects

### ISSUE THREAD

**Issue by gibertini** [aiidateam/aiida-core#3494] opened 2019-10-31 13:20 UTC
It seems like the equal to operator (==) is not working between node objects in a verdi shell. 
For instance if I do
`In [1]: c = load_node(1)`
`In [2]: d = load_node(1)`
I get  then 
`In [3]: c == d`
`Out[3]: False`
while I would have expected it to give `True`.
This means for instance that if I have a list of nodes, the `remove` method does not work.

It would be good make the equal operator work.

**Comment by sphuber** [comment] 2019-10-31 13:51
This is a duplicate of #1917 . I remember us having a discussion about this at the time and there potentially being a downside to having the behavior you describe, but I cannot remember. Also did not describe it in the other issue though.

**Comment by ltalirz** [comment] 2020-02-03 15:11
Closing, continue discussion in #1917

**Closed by ltalirz** 2020-02-03 15:11 UTC
Labels: type/duplicate
