### ISSUE TITLE
Misleading output of `verdi archive create --test-run`

### ISSUE THREAD

**Issue by danielhollas** [aiidateam/aiida-core#6312] opened 2024-03-13 16:02 UTC
### Describe the bug

Running `aiida archive create --test-run -N XXX -- archive.aiida` gave me the following output

```
Report: Validating Nodes                                                                                                                                                                                           
Report: Test Run: Stopping before archive creation
Report: Archive would be created with:
----------------  ---
users               1
computers           1
nodes             103
logs               41
links             305
Repository Files   79
----------------  ---
Success: wrote the export archive file to archive.aiida
```

The last line is clearly not true since no file has been generated.

---

- Operating system [e.g. Linux]:
- Python version [e.g. 3.9]:
- aiida-core version [e.g. 2.4.0]:

I haven't reproduced it on master branch yet. I am happy to take this on if this is indeed still an issue.

**Comment by sphuber** [comment] 2024-03-13 17:24
This is a duplicate of #5980

**Closed by sphuber** 2024-03-13 17:24 UTC
Labels: type/bug, type/duplicate

**Comment by danielhollas** [comment] 2024-03-13 17:29
Ah, right. Thanks for catching that, I should have searched first. I assumed that a minor thing like this would have been fixed by now if it was reported. :joy: Feel free to assign me #5980. I'll fix it in the next few weeks.
