### ISSUE TITLE
"verdi code" does not accept labels

### ISSUE THREAD

**Issue by dev-zero** [aiidateam/aiida-core#3656] opened 2019-12-12 21:08 UTC
while for computers one can do `verdi computer show myhost` after configuring it seems that the whole `verdi code` does not (transparently) work with labels:

```
(aiida) tiziano@scarlet ~/work/aiida $ verdi code setup
Info: enter "?" for help
Info: enter "!" to ignore the default and set no value
Label: add
Description []: 
Default calculation input plugin: ?
Info: Default calculation plugin to use for this code.
Select one of:
	arithmetic.add 
	templatereplacer 
Default calculation input plugin: arithmetic.add
Installed on target computer? [True]: 
Computer: localhost
Remote absolute path: /home/tiziano/work/aiida/aiida_core/.ci/add.sh
Success: Code<14> add@localhost created
(aiida) tiziano@scarlet ~/work/aiida $ verdi code show add
Usage: verdi code show [OPTIONS] CODE

Error: Invalid value for "CODE": no Code found with UUID<add>: No result was found
(aiida) tiziano@scarlet ~/work/aiida $ verdi code list
# List of configured codes:
# (use 'verdi code show CODEID' to see the details)
* pk 14 - add@localhost
(aiida) tiziano@scarlet ~/work/aiida $ verdi code show 14
--------------------  ----------------------------------------------
PK                    14
UUID                  1069c264-aced-463e-ab5f-877817f5a5bb
Label                 add
Description
Default plugin        arithmetic.add
Type                  remote
Remote machine        localhost
Remote absolute path  /home/tiziano/work/aiida/aiida_core/.ci/add.sh
Prepend text          No prepend text
Append text           No append text
--------------------  ----------------------------------------------
```

... the same goes for the `load_code(...)` helper which I would expect to take labels since I've configured one.

**Comment by sphuber** [comment] 2019-12-12 21:12
It actually can load from label, the hint is in the error message:
```
Error: Invalid value for "CODE": no Code found with UUID<add>: No result was found
```
note that it says `UUID<add>`. It interprets (incorrectly) the identifier as a UUID, because it is a valid hexadecimal. See [documentation](https://aiida-core.readthedocs.io/en/latest/verdi/verdi_user_guide.html#cli-concepts) for more details on how type inference happens.
To break the ambiguity you can use an exclamation mark, i.e.:
```
verdi code show add!
```
will work

**Comment by dev-zero** [comment] 2019-12-12 21:17
proposal: when no match could be done with PK or UUID, do a match by label

**Comment by dev-zero** [comment] 2019-12-12 21:18
@sphuber I hope you agree that if a user just setup a code named "add" he should be able to do "show add", right?

**Comment by sphuber** [comment] 2019-12-13 08:05
Yes, when just considering this example that would clearly be the more convenient behavior. However, I think by changing this behavior one can be unpleasantly surprised in other situation. A person might type a partial UUID, but accidentally mistype it and if this happens to match a label, that entity is returned instead. Note that all this logic does not just apply to `Code` instances, but to all nodes, computers, users, groups and what have you. So I am not sure

**Comment by ltalirz** [comment] 2020-02-03 15:16
This is a duplicate of https://github.com/aiidateam/aiida-core/issues/3346

Potential ways forward are described there, please continue discussion there.

**Closed by ltalirz** 2020-02-03 15:16 UTC
Labels: requires discussion, topic/verdi, type/duplicate, type/feature request
