### ISSUE TITLE
`verdi code duplicate` loses "Prepend text"

### ISSUE THREAD

**Issue by dev-zero** [aiidateam/aiida-core#4943] opened 2021-05-14 07:46 UTC
### Describe the bug

When duplicating a code the "Prepend text" in the editor is correctly prefilled from the source, but when simply saving it the duplicated code is missing the "Prepend text"

### Steps to reproduce

```console
(aiida) tiziano@tcpc18 ~/work/aiida $ verdi code show cp2k-8.1@eiger
--------------------  --------------------------------------------------------------------------
PK                    613
UUID                  b5c02f2f-3531-482c-ad82-6878669c02b8
Label                 cp2k-8.1
Description           CP2K as provided by CSCS
Default plugin        cp2k
Type                  remote
Remote machine        eiger
Remote absolute path  /apps/eiger/UES/jenkins/1.4.0/software/CP2K/8.1-cpeGNU-21.04/bin/cp2k.psmp
Prepend text          module load cpeGNU
                      module load CP2K/8.1
Append text
--------------------  --------------------------------------------------------------------------
(aiida) tiziano@tcpc18 ~/work/aiida $ verdi code duplicate cp2k-8.1@eiger
Info: enter "?" for help
Info: enter "!" to ignore the default and set no value
Label [cp2k-8.1]: cp2k-8.1-test
Description [CP2K as provided by CSCS]: 
Default calculation input plugin [cp2k]: 
Installed on target computer? [True]: 
Computer [eiger]: 
Remote absolute path [/apps/eiger/UES/jenkins/1.4.0/software/CP2K/8.1-cpeGNU-21.04/bin/cp2k.psmp]: 
YouCompleteMe unavailable: requires Vim 8.1.2269+.
Press ENTER or type command to continue
YouCompleteMe unavailable: requires Vim 8.1.2269+.
Press ENTER or type command to continue
Success: Code<661> cp2k-8.1-test@eiger created
(aiida) tiziano@tcpc18 ~/work/aiida $ verdi code show cp2k-8.1-test@eiger
--------------------  --------------------------------------------------------------------------
PK                    661
UUID                  ef2293db-95b7-4da1-99e9-44c727ea371d
Label                 cp2k-8.1-test
Description           CP2K as provided by CSCS
Default plugin        cp2k
Type                  remote
Remote machine        eiger
Remote absolute path  /apps/eiger/UES/jenkins/1.4.0/software/CP2K/8.1-cpeGNU-21.04/bin/cp2k.psmp
Prepend text
Append text
--------------------  --------------------------------------------------------------------------
```

### Your environment

- Operating system [e.g. Linux]: openSUSE LEAP 15.2
- Python version [e.g. 3.7.1]: 3.9.5
- aiida-core version [e.g. 1.2.1]:403f7e7d896f8408d0cacee9fe41c030a1072eaf

Other relevant software versions, e.g. Postres & RabbitMQ

**Comment by zhubonan** [comment] 2021-05-17 09:55
> YouCompleteMe unavailable: requires Vim 8.1.2269+.

seems to be the cruplit.

Did you see your text editor launched with the `prepend_text`, `append_text` text prefilled? 
The same command works fine for me consistently for many aiida version. I am on Ubuntu 18.04 and the default editor is Vim 8.0 patch 1-1453.

**Comment by dev-zero** [comment] 2021-05-17 10:27
> > YouCompleteMe unavailable: requires Vim 8.1.2269+.
> 
> seems to be the cruplit.

Why do you think so?

> Did you see your text editor launched with the `prepend_text`, `append_text` text prefilled?
> The same command works fine for me consistently for many aiida version. I am on Ubuntu 18.04 and the default editor is Vim 8.0 patch 1-1453.

Yes. I got the editor open with the preloaded text. Closed it again without editing anything.
So no, the editor didn't crash.

**Comment by dev-zero** [comment] 2021-05-17 13:56
Ok, I got rid of that warning, yet still same behaviour, also for `verdi computer duplicate`.

**Comment by dev-zero** [comment] 2021-05-17 13:57
Note: if I change something (instead of simply doing `:wq`) the text is there.

**Comment by sphuber** [comment] 2022-04-28 08:21
I also cannot reproduce this with vim 8.1 on Ubuntu 20.04. It is difficult to debug without being able to reproduce. I will be closing this for now. If you can reproduce it with another editor on your machine and provide some more details, feel free to reopen

**Closed by sphuber** 2022-04-28 08:21 UTC
Labels: type/bug
