### ISSUE TITLE
Keeping dependencies up-to-date

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#4799] opened 2021-03-09 22:19 UTC
To my knowledge we do no formal tracking of dependecy updating,
in fact this seems a bit of an oversight of https://github.com/aiidateam/AEP/tree/master/002_dependency_management.

The prominent tool for updating such dependencies is Dependabot, although I note this will create a PR for every patch version update (that you cannot opt out of https://github.com/dependabot/dependabot-core/issues/2219), which may be burdesome for the number of dependencies we have?

Alternatively, I've added code below and the generated table, which you could keep up-to-date manually or with a GitHub Action and something like https://github.com/marketplace/actions/create-or-update-comment, then also action manually.

Looking at the table, most packages are in decent shape, the one that sticks out to me though is `Django` being a major release behind (https://docs.djangoproject.com/en/3.1/releases/3.0/).
Also `aiormq`/`pamqp` are a major release behind, but they are pinned by `aio-pika` (all dependencies of `kiwipy`)

| name                            | current    | newest    |
|---------------------------------|------------|-----------|
| monty                           | 4.0.2      | 2021.3.3  |
| pytz                            | 2019.3     | 2021.1    |
| seekpath                        | 1.9.7      | 2.0.1     |
| aldjemy                         | 0.9.1      | 1.0.0     |
| PyMySQL                         | 0.9.3      | 1.0.2     |
| idna                            | 2.10       | 3.1       |
| pamqp                           | 2.3.0      | 3.0.1     |
| pymatgen                        | 2021.2.8.1 | 2022.0.4  |
| Django                          | 2.2.18     | 3.1.7     |
| aiormq                          | 3.3.1      | 4.2.0     |
| aniso8601                       | 8.1.1      | 9.0.1     |
| coverage                        | 4.5.4      | 5.5       |
| PyYAML                          | 5.1.2      | 5.4.1     |
| Sphinx                          | 3.2.1      | 3.5.2     |
| tqdm                            | 4.56.0     | 4.59.0    |
| ipykernel                       | 5.4.3      | 5.5.0     |
| Pygments                        | 2.7.4      | 2.8.1     |
| docutils                        | 0.15.2     | 0.16      |
| nest-asyncio                    | 1.4.3      | 1.5.1     |
| aio-pika                        | 6.7.1      | 6.8.0     |
| defusedxml                      | 0.6.0      | 0.7.1     |
| mpmath                          | 1.1.0      | 1.2.1     |
| wrapt                           | 1.11.2     | 1.12.1    |
| ipython                         | 7.20.0     | 7.21.0    |
| pg8000                          | 1.17.0     | 1.18.0    |
| pgsu                            | 0.1.0      | 0.2.0     |
| pytest-cov                      | 2.10.1     | 2.11.1    |
| cryptography                    | 3.4.3      | 3.4.6     |
| alembic                         | 1.5.4      | 1.5.6     |
| nbclient                        | 0.5.1      | 0.5.3     |
| Pillow                          | 8.1.0      | 8.1.2     |
| prompt-toolkit                  | 3.0.14     | 3.0.16    |
| scramp                          | 1.2.0      | 1.2.2     |
| sqlalchemy-diff                 | 0.1.3      | 0.1.5     |
| tabulate                        | 0.8.7      | 0.8.9     |
| cffi                            | 1.14.4     | 1.14.5    |
| pandas                          | 1.2.2      | 1.2.3     |
| pyzmq                           | 22.0.2     | 22.0.3    |
| ruamel.yaml                     | 0.16.12    | 0.16.13   |
| scipy                           | 1.6.0      | 1.6.1     |
| sphinxext-rediraffe             | 0.2.5      | 0.2.6     |
| upf-to-json                     | 0.9.2      | 0.9.3     |
| aiida-export-migration-tests    | 0.9.0      | 0.9.0     |
| alabaster                       | 0.7.12     | 0.7.12    |
| archive-path                    | 0.2.1      | 0.2.1     |
| argon2-cffi                     | 20.1.0     | 20.1.0    |
| ase                             | 3.21.1     | 3.21.1    |
| async-generator                 | 1.10       | 1.10      |
| attrs                           | 20.3.0     | 20.3.0    |
| Babel                           | 2.9.0      | 2.9.0     |
| backcall                        | 0.2.0      | 0.2.0     |
| bcrypt                          | 3.2.0      | 3.2.0     |
| bleach                          | 3.3.0      | 3.3.0     |
| certifi                         | 2020.12.5  | 2020.12.5 |
| chardet                         | 4.0.0      | 4.0.0     |
| circus                          | 0.17.1     | 0.17.1    |
| click                           | 7.1.2      | 7.1.2     |
| click-completion                | 0.5.2      | 0.5.2     |
| click-config-file               | 0.6.0      | 0.6.0     |
| click-spinner                   | 0.1.10     | 0.1.10    |
| configobj                       | 5.0.6      | 5.0.6     |
| cycler                          | 0.10.0     | 0.10.0    |
| decorator                       | 4.4.2      | 4.4.2     |
| deprecation                     | 2.1.0      | 2.1.0     |
| entrypoints                     | 0.3        | 0.3       |
| ete3                            | 3.1.2      | 3.1.2     |
| Flask                           | 1.1.2      | 1.1.2     |
| Flask-Cors                      | 3.0.10     | 3.0.10    |
| Flask-RESTful                   | 0.3.8      | 0.3.8     |
| frozendict                      | 1.2        | 1.2       |
| future                          | 0.18.2     | 0.18.2    |
| graphviz                        | 0.16       | 0.16      |
| imagesize                       | 1.2.0      | 1.2.0     |
| iniconfig                       | 1.1.1      | 1.1.1     |
| ipython-genutils                | 0.2.0      | 0.2.0     |
| ipywidgets                      | 7.6.3      | 7.6.3     |
| itsdangerous                    | 1.1.0      | 1.1.0     |
| jedi                            | 0.18.0     | 0.18.0    |
| Jinja2                          | 2.11.3     | 2.11.3    |
| jsonschema                      | 3.2.0      | 3.2.0     |
| jupyter                         | 1.0.0      | 1.0.0     |
| jupyter-client                  | 6.1.11     | 6.1.11    |
| jupyter-console                 | 6.2.0      | 6.2.0     |
| jupyter-core                    | 4.7.1      | 4.7.1     |
| jupyterlab-pygments             | 0.1.2      | 0.1.2     |
| jupyterlab-widgets              | 1.0.0      | 1.0.0     |
| kiwipy                          | 0.7.4      | 0.7.4     |
| kiwisolver                      | 1.3.1      | 1.3.1     |
| Mako                            | 1.1.4      | 1.1.4     |
| MarkupSafe                      | 1.1.1      | 1.1.1     |
| matplotlib                      | 3.3.4      | 3.3.4     |
| mistune                         | 0.8.4      | 0.8.4     |
| multidict                       | 5.1.0      | 5.1.0     |
| nbconvert                       | 6.0.7      | 6.0.7     |
| nbformat                        | 5.1.2      | 5.1.2     |
| networkx                        | 2.5        | 2.5       |
| notebook                        | 6.2.0      | 6.2.0     |
| numpy                           | 1.20.1     | 1.20.1    |
| packaging                       | 20.9       | 20.9      |
| palettable                      | 3.3.0      | 3.3.0     |
| pandocfilters                   | 1.4.3      | 1.4.3     |
| paramiko                        | 2.7.2      | 2.7.2     |
| parso                           | 0.8.1      | 0.8.1     |
| pexpect                         | 4.8.0      | 4.8.0     |
| pgtest                          | 1.3.2      | 1.3.2     |
| pickleshare                     | 0.7.5      | 0.7.5     |
| plotly                          | 4.14.3     | 4.14.3    |
| pluggy                          | 0.13.1     | 0.13.1    |
| plumpy                          | 0.19.0     | 0.19.0    |
| prometheus-client               | 0.9.0      | 0.9.0     |
| psutil                          | 5.8.0      | 5.8.0     |
| psycopg2-binary                 | 2.8.6      | 2.8.6     |
| ptyprocess                      | 0.7.0      | 0.7.0     |
| py                              | 1.10.0     | 1.10.0    |
| py-cpuinfo                      | 7.0.0      | 7.0.0     |
| PyCifRW                         | 4.4.2      | 4.4.2     |
| pycparser                       | 2.20       | 2.20      |
| pydata-sphinx-theme             | 0.4.3      | 0.4.3     |
| pympler                         | 0.9        | 0.9       |
| PyNaCl                          | 1.4.0      | 1.4.0     |
| pyparsing                       | 2.4.7      | 2.4.7     |
| pyrsistent                      | 0.17.3     | 0.17.3    |
| pytest                          | 6.2.2      | 6.2.2     |
| pytest-asyncio                  | 0.14.0     | 0.14.0    |
| pytest-benchmark                | 3.2.3      | 3.2.3     |
| pytest-rerunfailures            | 9.1.1      | 9.1.1     |
| pytest-timeout                  | 1.4.2      | 1.4.2     |
| python-dateutil                 | 2.8.1      | 2.8.1     |
| python-editor                   | 1.0.4      | 1.0.4     |
| python-memcached                | 1.59       | 1.59      |
| pytray                          | 0.3.1      | 0.3.1     |
| qtconsole                       | 5.0.2      | 5.0.2     |
| QtPy                            | 1.9.0      | 1.9.0     |
| reentry                         | 1.3.2      | 1.3.2     |
| requests                        | 2.25.1     | 2.25.1    |
| retrying                        | 1.3.3      | 1.3.3     |
| ruamel.yaml.clib                | 0.2.2      | 0.2.2     |
| Send2Trash                      | 1.5.0      | 1.5.0     |
| shellingham                     | 1.4.0      | 1.4.0     |
| shortuuid                       | 1.0.1      | 1.0.1     |
| simplejson                      | 3.17.2     | 3.17.2    |
| six                             | 1.15.0     | 1.15.0    |
| snowballstemmer                 | 2.1.0      | 2.1.0     |
| spglib                          | 1.16.1     | 1.16.1    |
| sphinx-copybutton               | 0.3.1      | 0.3.1     |
| sphinx-notfound-page            | 0.6        | 0.6       |
| sphinx-panels                   | 0.5.2      | 0.5.2     |
| sphinxcontrib-applehelp         | 1.0.2      | 1.0.2     |
| sphinxcontrib-details-directive | 0.1.0      | 0.1.0     |
| sphinxcontrib-devhelp           | 1.0.2      | 1.0.2     |
| sphinxcontrib-htmlhelp          | 1.0.3      | 1.0.3     |
| sphinxcontrib-jsmath            | 1.0.1      | 1.0.1     |
| sphinxcontrib-qthelp            | 1.0.3      | 1.0.3     |
| sphinxcontrib-serializinghtml   | 1.1.4      | 1.1.4     |
| SQLAlchemy                      | 1.3.23     | 1.3.23    |
| SQLAlchemy-Utils                | 0.36.8     | 0.36.8    |
| sqlparse                        | 0.4.1      | 0.4.1     |
| sympy                           | 1.7.1      | 1.7.1     |
| terminado                       | 0.9.2      | 0.9.2     |
| testpath                        | 0.4.4      | 0.4.4     |
| toml                            | 0.10.2     | 0.10.2    |
| tornado                         | 6.1        | 6.1       |
| traitlets                       | 5.0.5      | 5.0.5     |
| tzlocal                         | 2.1        | 2.1       |
| uncertainties                   | 3.1.5      | 3.1.5     |
| urllib3                         | 1.26.3     | 1.26.3    |
| wcwidth                         | 0.2.5      | 0.2.5     |
| webencodings                    | 0.5.1      | 0.5.1     |
| Werkzeug                        | 1.0.1      | 1.0.1     |
| widgetsnbextension              | 3.5.1      | 3.5.1     |
| yarl                            | 1.6.3      | 1.6.3     |

```python
import json
from pathlib import Path
import requests

from packaging.version import parse
from tabulate import tabulate


def get_latest_version(name):
    req = requests.get(f'https://pypi.python.org/pypi/{name}/json')
    assert req.status_code == requests.codes.ok, "{name} PyPi download failed"
    data = json.loads(req.text.encode(req.encoding or "utf8"))
    return parse(data["info"]["version"])


def sort_versions(data):
    _, current, newest = data
    return ((1e4 * abs(current.major - newest.major)) +
            (1e2 * abs(current.minor - newest.minor)) +
            abs(current.micro - newest.micro))


path = Path("requirements/requirements-py-3.8.txt")
packages = dict([
    line.strip().split("==") for line in path.read_text("utf8").splitlines()
    if line
])
packages = [(name, parse(version), get_latest_version(name))
            for name, version in packages.items()]
packages = sorted(packages, key=sort_versions, reverse=True)

print(tabulate(packages, headers=["name", "current", "newest"], tablefmt="github"))
```

**Comment by csadorf** [comment] 2021-03-10 09:20
@chrisjsewell Thank you for the summary and especially the code snippet. I actually tried to implement something similar a while back, but never got around to actually finishing it. This is great.

I agree that we probably have to implement some process to more regularly update dependencies to later versions, however, I think there might also be a slight misunderstanding as to how dependencies are currently defined. With AEP-002 we identified `aiida-core` to be a hybrid between a library and an application which means that we try to aim supporting a large range of versions to ensure that AiiDA is easily install-able in various (application) contexts. To me this means that regularly updating our dependency constraints (as defined in `setup.json`) to the latest version makes little sense since as long we remain compatible there is no reason to tighten the constraint.

We use the `requirements-*` files to maintain a stable and reproducible development and testing environment (checked in the `continuous-integration` workflow and we test against the "latest" possible environment as part of the `test-install` workflow. This means we are

1. consistently testing against a stable set of dependencies (defined in `requirements-*.txt` files) which are infrequently and explicitly updated whenever we update our dependency constraints and
2. regularly testing against a rapidly changing set of dependencies as a user would find them on a fresh installation as part of the `test-install` workflow.

Whenever we need to constrain a dependency (e.g. by putting an upper limit on the supported version), I aim to also create a corresponding issue with the `topics/dependencies/constraint` label attached. In this way we track these constraints that should aim to loosen again.

However, I still agree that there is a gap. Since we predominantly use the compatible-release operator for our constraints, newly released incompatible versions are neither automatically tested nor is there any pressure within our development workflow to loosen these constraints unless the environment can no longer be resolved. I typically follow the larger packages (e.g. numpy) and then create a corresponding issue to support newer versions, but I do not do the same for the "smaller" packages.

My proposed solution is to implement some automation based on code similar to the snippet above that checks our constraints (defined in `setup.json`, not in `requirements-*`) and either automatically tries to expand them or at least notifies us that new incompatible versions have been released and we should aim to support them. Does that sound reasonable? I am open to suggestions. I also wonder whether dependabot might be able to support such a workflow.

**Comment by chrisjsewell** [comment] 2021-03-10 10:04
> This is great.

cheers 😄 

> However, I think there might also be a slight misunderstanding

Oh no I understand we want to support a range, however ...

> Whenever we need to constrain a dependency (e.g. by putting an upper limit on the supported version), I aim to also create a corresponding issue with the topics/dependencies/constraint label attached. In this way we track these constraints that should aim to loosen again.

but this is not really true though (as you allude to later); because in `setup.json` we constrain **all** of our dependencies to at least a major version (minor if the version is less than 1.0.0) and there is no issues open to track them.

> My proposed solution is to ...

yep sounds good cheers 👍, the main thing is that we are at least aware when we are a major version behind any important dependencies (like django) and hopefully working towards bridging the gap (which, as semver dictates, will likely mean changes in our code to use the changed API and will probably require us dropping support for the older version). We want to be "compatible", but not at the cost of missing important security/performance updates.

>  I also wonder whether dependabot might be able to support such a workflow.

not sure off-hand, I leave you to experiment 😬

**Closed** 2021-08-03 10:19 UTC
Labels: topic/dependencies
