### ISSUE TITLE
`aiida_profile` test fixture leaves unclosed file in test suits

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#6271] opened 2024-02-01 07:15 UTC
A warning exception in AiiDAlab test, I can confirm it comes from the `pytest_fixture` and from `aiida_profile` of `aiida.manage.tests.pytest_fixtures`. 

With a dummy test in `aiidalab-widgets-base` only load the `aiida.manage.tests.pytest_fixtures`. It appears after we turn on pytest option of show warning as error. 

After I comment out the `aiida_profile` fixture, this warning disappeared.

```
tests/test_a.py::test_a Exception ignored in: <_io.FileIO name=6 mode='rb' closefd=True>
Traceback (most recent call last):
  File "/home/jyu/micromamba/envs/aiidalab-dev/lib/python3.9/site-packages/_pytest/unraisableexception.py", line 59, in __exit__
    del self.unraisable
ResourceWarning: unclosed file <_io.BufferedReader name=6>
Exception ignored in: <_io.FileIO name=8 mode='rb' closefd=True>
Traceback (most recent call last):
  File "/home/jyu/micromamba/envs/aiidalab-dev/lib/python3.9/site-packages/_pytest/unraisableexception.py", line 59, in __exit__
    del self.unraisable
ResourceWarning: unclosed file <_io.BufferedReader name=8>
```

_Originally posted by @unkcpz in https://github.com/aiidateam/aiida-core/issues/6254#issuecomment-1919248687_

Mirror of the issue https://github.com/aiidalab/aiidalab-widgets-base/issues/551.

**Comment by sphuber** [comment] 2024-04-21 06:39
I cannot reproduce this with the new fixtures in `aiida.tools.pytest_fixtures` so I am closing this for now

**Closed by sphuber** 2024-04-21 06:39 UTC
