### ISSUE TITLE
Adding a group fails in a database with no User nodes

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#3132] opened 2019-07-05 09:57 UTC
Bit of a niche issue this, but I'll put it here just for kicks.
After running unit tests for aiida-core, obviously it clears the database. I then tried to import an `export.tar.gz`, that required a migration. This failed, because for `Group.__init__` there's no User node available:

```python
Error: an exception occurred while importing the archive export.tar.gz
Traceback (most recent call last):
  File "/Users/cjs14/GitHub/aiida_core_develop/aiida/cmdline/commands/cmd_import.py", line 67, in _try_import
    import_data(file_to_import, group, **kwargs)
  File "/Users/cjs14/GitHub/aiida_core_develop/aiida/tools/importexport/dbimport/__init__.py", line 54, in import_data
    return import_data_dj(in_path, group=group, silent=silent, **kwargs)
  File "/Users/cjs14/GitHub/aiida_core_develop/aiida/tools/importexport/dbimport/backends/django/__init__.py", line 576, in import_data_dj
    group = Group(label=group_label, type_string=IMPORTGROUP_TYPE).store()
  File "/Users/cjs14/GitHub/aiida_core_develop/aiida/orm/groups.py", line 120, in __init__
    type_check(user, users.User)
  File "/Users/cjs14/GitHub/aiida_core_develop/aiida/common/lang.py", line 80, in type_check
    raise TypeError(msg)
TypeError: Got object of type '<class 'NoneType'>', expecting '<class 'aiida.orm.users.User'>'
```

**Comment by CasperWA** [comment] 2019-07-05 11:24
It seems it wasn't the migration that failed, but the subsequent import. Specifically upon creating a Group (as you correctly state).

I believe this issue is related to the removal of the "default User", since if no user is supplied to the Group initialization, then it attempts to retrieve the default User. I remember we had this issue surfacing generally some time ago, but cannot find the issue number now.

When importing, are you using your test profile?
Can you check if you have a default user (`verdi user list`, I think it's the one that is starred or bold here?). Or perhaps try in `verdi shell` (using the profile you're using for the import) to write:

```python
from aiida.orm import User
user = User.objects.get_default()
```

and check what `user` is.

**Comment by CasperWA** [comment] 2019-07-05 11:26
By the way, what the import is doing here, is creating the standard "import group" wherein all imported Nodes are added 😃 It is not importing a Group from you archive at this stage.

**Comment by chrisjsewell** [comment] 2019-07-05 11:38
Oh yeh I know 👍. But `user` is `None` there, because there's literally no node in the database, including User. Basically, if you add after here
https://github.com/aiidateam/aiida-core/blob/3550155af696c22f68fc8c6dc94e3ac4d6d36983/aiida/orm/groups.py#L114

```python 
        if user is None:
            from aiida.manage.configuration import get_profile
            profile = get_profile()
            email = profile.default_user
            user = users.User(backend=backend, email=email)
```

Then that works :)

**Comment by CasperWA** [comment] 2019-07-05 12:33
Right, but the problem is that, I think, the default user should never actually be removed? @sphuber or @ltalirz, do you remember what we settled on for this "default user" issue?

**Comment by ltalirz** [comment] 2019-07-05 12:45
It was originally @szoupanos who insisted that an empty test database should not have a user (to be sure that tests did not depend on one being present).

This effectively means you can't do anything on the verdi shell (or, as @chrisjsewell mentions, import things). Essentially, it makes a test profile a profile *for running tests only*.

I also found this problematic since this was different before, and it simply happens that people want to do things on a test profile.
For me it would not be a problem to reintroduce a default user there.

In the medium term, my view is that the test profile will anyhow disappear for most people, since it will be created on the fly when running the tests (as we already do for testing plugins).

**Comment by CasperWA** [comment] 2019-07-05 12:52
It should be noted that you can still import archives on a test profile, but it has to be in a test 😄, i.e., everything first has to be "primed" using AiiDA's current test system.

But if you are simply interested in playing around with an archive and don't want it to interfere with anything, I would suggest you make a separate (non-test) profile for it - including a new database.

**Comment by ltalirz** [comment] 2019-07-05 12:56
So I'll be closing this for the time being - if anyone feels very strongly about always leaving a user in a test profile we can reopen.

**Comment by chrisjsewell** [comment] 2019-07-05 12:56
Yeh exactly, I was just too lazy to do that 😆

**Closed by ltalirz** 2019-07-05 12:56 UTC
