### ISSUE TITLE
`Config.delete_profile` is leaking implementation details of `PsqlDosBackend`

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#5515] opened 2022-05-04 11:23 UTC
As such, it would fail for a profile with any other storage backend. The functionality should really be implemented on `StorageBackend.erase()` (which doesn't exist yet) and `Config.delete_profile` should simply call this.

**Comment by chrisjsewell** [comment] 2022-05-04 12:01
this is a duplicate of #5353

**Closed** 2023-12-14 16:29 UTC
Labels: topic/repository, topic/config, priority/important, type/refactoring, topic/storage
