### ISSUE TITLE
verdi data bands export broken

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#2462] opened 2019-02-07 20:02 UTC
`verdi data bands export` offers a number of format options:
```
$ verdi data bands export 215
Default format is not defined, please specify.
Valid formats are:
  agr
  agr_batch
  dat_blocks
  dat_multicolumn
  gnuplot
  json
  mpl_pdf
  mpl_png
  mpl_singlefile
  mpl_withjson
```

At least the `gnuplot` and `mpl_*` options don't seem to work:

```
$ verdi data bands export 215 --format mpl_pdf  -o bands.pdf
Traceback (most recent call last):
  File "/Users/leopold/Applications/miniconda3/envs/aiida_production/bin/verdi", line 11, in <module>
    sys.exit(run())
  File "/Users/leopold/Applications/miniconda3/envs/aiida_production/lib/python2.7/site-packages/aiida/cmdline/verdilib.py", line 1050, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_production/lib/python2.7/site-packages/aiida/cmdline/verdilib.py", line 1035, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/Users/leopold/Applications/miniconda3/envs/aiida_production/lib/python2.7/site-packages/aiida/cmdline/baseclass.py", line 137, in run
    function_to_call(*args[1:])
  File "/Users/leopold/Applications/miniconda3/envs/aiida_production/lib/python2.7/site-packages/aiida/cmdline/baseclass.py", line 217, in run
    function_to_call(*args[1:])
  File "/Users/leopold/Applications/miniconda3/envs/aiida_production/lib/python2.7/site-packages/aiida/cmdline/commands/data.py", line 441, in export
    func(n, output_fname=output_fname, overwrite=overwrite, **parsed_args)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_production/lib/python2.7/site-packages/aiida/cmdline/commands/data.py", line 1031, in _export_mpl_pdf
    other_args=kwargs)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_production/lib/python2.7/site-packages/aiida/cmdline/commands/data.py", line 463, in print_or_store
    output_fname, fileformat=fileformat, overwrite=overwrite, **other_args)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_production/lib/python2.7/site-packages/aiida/orm/data/__init__.py", line 194, in export
    fileformat, main_file_name=path, **kwargs)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_production/lib/python2.7/site-packages/aiida/orm/data/__init__.py", line 155, in _exportstring
    return func(main_file_name=main_file_name, **kwargs)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_production/lib/python2.7/site-packages/aiida/orm/data/array/bands.py", line 1017, in _prepare_mpl_pdf
    all_data = self._matplotlib_get_dict(*args, **kwargs)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_production/lib/python2.7/site-packages/aiida/orm/data/array/bands.py", line 807, in _matplotlib_get_dict
    tick_pos, tick_labels = zip(*labels)
ValueError: need more than 0 values to unpack
```

Or
```
$ verdi data bands export 215 --format gnuplot -o bands.gnu
$ gnuplot bands.gnu
"bands.gnu" line 35: Can't plot with an empty x range!
```

I attach an export file with the corresponding BandsData node.

[bands.zip](https://github.com/aiidateam/aiida_core/files/2842467/bands.zip)

**Comment by yakutovicha** [comment] 2019-05-06 12:46
@ltalirz  I guess the issue is related to https://github.com/aiidateam/aiida_core/issues/2756, which is now fixed.

At least in my case it is now working fine.

**Comment by sphuber** [comment] 2019-10-11 11:55
I am not sure that this is the same bug as in #2756 which really is a bug in the export functionality. The export content was being encoded to a bytestring twice. Here it may just be a problem with the particular `BandsData` instance. It may just be that the `labels` variable is empty because the `KpointsData` set for the `BandsData` node does not define labels, which are optional attributes

**Comment by unkcpz** [comment] 2020-02-24 13:33
I guess the issue comes from the data dimension of your `BandsData` instance @ltalirz. The shape of the `array|bands` is [1, 396], in this case, energy levels should be plot rather than the bands. 
This is the attempt to solve the problem https://github.com/aiidateam/aiida-core/pull/3798 (only for mpl export). However, the solution needs to extent for different export methods.

**Comment by unkcpz** [comment] 2020-02-24 13:35
There seems to be no specific way to draw the energy level for 0D systems. Such usage scenarios should not be uncommon.

**Comment by ltalirz** [comment] 2020-02-24 15:32
Thanks for looking into this @unkcpz and figuring out the problem.

Just to clarify - we're not necessarily talking about 0d systems, but "band structures" that contain only a single k-point (could be a Gamma-point calculation of a crystal).

**Closed** 2020-04-12 18:54 UTC
Labels: aiida-core 0.x, good first issue, type/bug
