### ISSUE TITLE
Add support for type hint parsing in automatic process spec determination for process functions

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4116] opened 2020-05-26 06:47 UTC
Now that we support only Python versions that have type hinting for function signatures, we could maybe inspect those hints to improve the automatically generated process spec to set the `valid_type` based on it. This will improve for example the output of `verdi plugin list` with the description of process functions which now will always just show `Data` as the required type.

**Comment by greschd** [comment] 2020-05-26 08:05
Dupe of #3569?

**Closed** 2020-05-26 08:10 UTC
Labels: priority/nice-to-have, topic/processes, type/accepted feature, type/duplicate
