### ISSUE TITLE
Randomly failing test (in the backup_script tests)

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#2134] opened 2018-10-26 14:18 UTC
https://travis-ci.org/aiidateam/aiida_core/jobs/446675963
```
======================================================================
FAIL: test_integration (aiida.backends.tests.backup_script.TestBackupScriptIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/aiidateam/aiida_core/aiida/backends/tests/backup_script.py", line 340, in test_integration
    "The backed-up repository has differences "
AssertionError: False is not true : The backed-up repository has differences to the original one.
----------------------------------------------------------------------
```
Any idea why this happens? Could you critically check the test code to see if there are cases in which can happen but it's not a failed test? Can you maybe also improve the output of the test to tell exactly what changed?

**Comment by szoupanos** [comment] 2018-10-29 19:36
I ran it 16 times locally without being able to reproduce the problem. With PR #2141, I improve the messages of aiida.common.utils.are_dir_trees_equal function in order to have more info the next time that it fails.

**Comment by sphuber** [comment] 2018-10-30 10:50
The error message has been changed to give more detail in PR #2141 
If you encountered another failure and was directed to this issue, please
post the error message and reopen this issue, such that the origin of the
failing test can be determined and fixed.

**Comment by giovannipizzi** [comment] 2018-11-10 07:01
This happened again: https://travis-ci.org/aiidateam/aiida_core/jobs/452782213

**Comment by sphuber** [comment] 2018-11-16 10:00
```
======================================================================
FAIL: test_integration (aiida.backends.tests.backup_script.TestBackupScriptIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/aiidateam/aiida_core/aiida/backends/tests/backup_script.py", line 341, in test_integration
    + ". If the test fails, report it in issue #2134.")
AssertionError: False is not true : The backed-up repository has differences to the original one. Left directory: /tmp/test_repository_test_sqlalchemy/repository/node, right directory: /tmp/tmp87nq149k/.aiida/backup/backup_dest/repository/node, files only in left directory: ['5d', 'cd'], files only in right directory: [], not comparable files: []. If the test fails, report it in issue #2134.
```

**Comment by CasperWA** [comment] 2019-04-05 15:59
For PR #2478.

```shell
======================================================================
FAIL: test_integration (aiida.backends.tests.test_backup_script.TestBackupScriptIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/aiidateam/aiida_core/aiida/backends/tests/test_backup_script.py", line 342, in test_integration
    + ". If the test fails, report it in issue #2134.")
AssertionError: False is not true : The backed-up repository has differences to the original one. Left directory: /tmp/test_repository_test_sqlalchemy/repository/node, right directory: /tmp/tmp_orf2eif/.aiida/backup/backup_dest/repository/node, files only in left directory: ['1d', '26'], files only in right directory: [], not comparable files: []. If the test fails, report it in issue #2134.
```

**Comment by ltalirz** [comment] 2019-04-26 22:08
Aaaand again https://travis-ci.org/aiidateam/aiida_core/jobs/525121123#L3007

**Comment by ltalirz** [comment] 2019-04-26 22:18
It seems to me the issues is always that there are additional data in the repository (left folder), never the other one.
Are there perhaps other tests that write to the same repository?
Since test order is not guaranteed, this might sometimes cause issues and sometimes not.

@szoupanos The solution could simply be to clean the repository before this test (?) I don't know the details of what this test does, happy to make the change if I get directions (or someone more familiar with the test can do it)

**Comment by CasperWA** [comment] 2019-09-17 14:32
I had this test fail just now for PR #3242.
Travis details:
Python: 3.6
TEST_AIIDA_BACKEND=django TEST_TYPE="tests"

**Comment by csadorf** [comment] 2019-10-09 12:09
This test just failed for PR #3409 .
https://travis-ci.org/aiidateam/aiida-core/jobs/595562156

```
======================================================================
FAIL: test_integration (aiida.backends.tests.manage.backup.test_backup_script.TestBackupScriptIntegration)
Test integration
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/aiidateam/aiida-core/aiida/backends/tests/manage/backup/test_backup_script.py", line 318, in test_integration
    '. If the test fails, report it in issue #2134.'
AssertionError: False is not true : The backed-up repository has differences to the original one. Left directory: /tmp/test_repository_test_sqlalchemy/repository/node, right directory: /tmp/tmpj_2rce5v/.aiida/backup/backup_dest/repository/node, files only in left directory: ['28'],

**Comment by CasperWA** [comment] 2019-10-10 18:05
Just failed for PR #3386 
Python: 3.6
TEST_AIIDA_BACKEND=sqlalchemy TEST_TYPE="tests"

```
FAIL: test_integration (aiida.backends.tests.manage.backup.test_backup_script.TestBackupScriptIntegration)
Test integration
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/aiidateam/aiida-core/aiida/backends/tests/manage/backup/test_backup_script.py", line 318, in test_integration
    '. If the test fails, report it in issue #2134.'
AssertionError: False is not true : The backed-up repository has differences to the original one. Left directory: /tmp/test_repository_test_sqlalchemy/repository/node, right directory: /tmp/tmp49fkgdrm/.aiida/backup/backup_dest/repository/node, files only in left directory: ['68'], files only in right directory: [], not comparable files: []. If the test fails, report it in issue #2134.
```

**Comment by asle85** [comment] 2019-11-07 13:00
This test failed for PR #3516
Python: 3.6
AIIDA_TEST_BACKEND=django TEST_TYPE="tests"

```
======================================================================
FAIL: test_integration (aiida.backends.tests.manage.backup.test_backup_script.TestBackupScriptIntegration)
Test integration
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/aiidateam/aiida-core/aiida/backends/tests/manage/backup/test_backup_script.py", line 318, in test_integration
    '. If the test fails, report it in issue #2134.'
AssertionError: False is not true : The backed-up repository has differences to the original one. Left directory: /tmp/test_repository_test_django/repository/node, right directory: /tmp/tmpwb_wky3j/.aiida/backup/backup_dest/repository/node, files only in left directory: ['d1'], files only in right directory: [], not comparable files: []. If the test fails, report it in issue #2134.
```

**Comment by greschd** [comment] 2019-12-10 22:11
Test failed for PR #3642 [build](https://github.com/aiidateam/aiida-core/pull/3642/checks?check_run_id=342747254)
Python: 3.7
backend:sqlalchemy, tests

```
======================================================================
FAIL: test_integration (aiida.backends.tests.manage.backup.test_backup_script.TestBackupScriptIntegration)
Test integration
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/aiida-core/aiida-core/aiida/backends/tests/manage/backup/test_backup_script.py", line 315, in test_integration
    '. If the test fails, report it in issue #2134.'
AssertionError: False is not true : The backed-up repository has differences to the original one. Left directory: /tmp/test_repository_test_sqlalchemy/repository/node, right directory: /tmp/tmp8uiijj6d/.aiida/backup/backup_dest/repository/node, files only in left directory: ['28'], files only in right directory: [], not comparable files: []. If the test fails, report it in issue #2134.

----------------------------------------------------------------------
```

**Comment by sphuber** [comment] 2020-10-04 15:03
This will become obsolete once the current backup implementation will be removed and replaced with the new repository implementation which is slated for `v2.0.0`.

**Comment by ltalirz** [comment] 2021-03-11 13:05
While the underlying issue (interaction with the test infrastructure/...) may still exist, it seems that marking this test as flaky and introducing max. 2 reruns in https://github.com/aiidateam/aiida-core/commit/1fdcf0f6911ec92f7f79d3f6f88ab6806dbd3dec has stopped this test from causing interruptions to the testing infrastructure for over one year.

I suggest we retain the reference to this issue in the code and, at one point, can go back through all the "flaky" tests in the codebase.
However, I think we won't be spending extra effort on this test until that time and can close this issue.

**Closed by ltalirz** 2021-03-11 13:05 UTC
Labels: topic/testing, type/bug

**Comment by sphuber** [comment] 2021-03-11 14:02
Anyway, this test will be removed with #4345 as the backup script will be obsolete
