### ISSUE TITLE
`builder` returns wrong values of inputs defaults when namespaces are used in `expose_inputs`

### ISSUE THREAD

**Issue by bosonie** [aiidateam/aiida-core#5263] opened 2021-12-08 21:15 UTC
### Describe the bug

Several misleading behaviors (fairly weird I would say) have been detected when playing with default of inputs ports that have been exposed inside a namespace. See below to reproduce them.

### Steps to reproduce

In verdi shell:
```
from aiida import orm
from aiida.engine import WorkChain
class ClassA(WorkChain):
    @classmethod
    def define(cls, spec):
        super().define(spec)
        spec.input("www",valid_type=Float,default=lambda: Float(1.0))
        spec.outline(cls.brun)
    def brun(self):
        return None

class ClassB(WorkChain):
    @classmethod
    def define(cls, spec):
        super().define(spec)
        spec.expose_inputs(ClassA,namespace="dddd")
        spec.expose_inputs(ClassA,namespace="aaaa")
        spec.inputs["dddd"]["www"].default = lambda: Float(33.0)
        spec.outline(cls.run)

    def run(self):
        self.report("w")

b=ClassB.get_builder()
```
First of all, typing `b.www()` returns something. It shouldn't be since the input is exposed in a namespace.
Second, `b.dddd.www()` does not return the correct default. Please note that the error is introduced only when the line `spec.expose_inputs(ClassA,namespace="aaaa")` is present. If removed, the default is correctly returned.

### Expected behavior
Should be clear from above

### Important node
The bug is only on the value returned by the builder. In fact `ClassB.spec().inputs._ports["dddd"]["www"].default()` correctly shows the right default. Same for `b._process_spec.inputs._ports["dddd"]["www"].default()`. And also, when the workchain is launched, the correct inputs are used.
Therefore it only seems a problem of "updating" what is returned by the "getter".

### Your environment

- Operating system [e.g. Linux]: Linux
- Python version [e.g. 3.7.1]: 3.7.10
- aiida-core version [e.g. 1.2.1]: 1.6.5

**Comment by sphuber** [comment] 2021-12-09 08:56
Thanks @bosonie . Can you have another look at your example and I cannot reproduce the problem.
```python
In [1]: from aiida import orm
   ...: from aiida.engine import WorkChain
   ...: class ClassA(WorkChain):
   ...:     @classmethod
   ...:     def define(cls, spec):
   ...:         super().define(spec)
   ...:         spec.input("www",valid_type=Float,default=lambda: Float(1.0))
   ...:         spec.outline(cls.brun)
   ...:     def brun(self):
   ...:         return None
   ...: 
   ...: class ClassB(WorkChain):
   ...:     @classmethod
   ...:     def define(cls, spec):
   ...:         super().define(spec)
   ...:         spec.expose_inputs(ClassA,namespace="dddd")
   ...:         spec.expose_inputs(ClassA,namespace="aaaa")
   ...:         spec.inputs["dddd"]["www"].default = lambda: Float(33.0)
   ...:         spec.outline(cls.run)
   ...: 
   ...:     def run(self):
   ...:         self.report("w")
   ...: 
   ...: b=ClassB.get_builder()

In [2]: b
Out[2]: {'metadata': {}, 'dddd': {'metadata': {}}, 'aaaa': {'metadata': {}}}

In [3]: b.www()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-087b93e24a03> in <module>
----> 1 b.www()

AttributeError: 'ProcessBuilder-1051c00d-78f5-4878-8f87-6254f37ee16' object has no attribute 'www'
```
The resulting namespace looks ok to me. And calling `b.www` doesn't return anything. I am not sure why you are trying to _call_ a member of the builder anyway? Was this a typo? Thought so initially, but then you do it again later in your post with `b.dddd.www()`.

**Comment by bosonie** [comment] 2021-12-09 09:02
The fact you call is due to the fact that the default is a `lambda`, so a function. In any case the same problem can be seen without a `lambda`, for instance when you have a `non_db` input port and therefore you define simple python types as defaults.
I confirm my findings. I repeated my example in another machine (fedora) and I get the same problem.

**Comment by sphuber** [comment] 2021-12-09 09:32
After looking at it some more, it is clear that this is a bug in 1.6.5 that was already fixed in `develop`. This is the same symptom of the bug reported in #4420 which was resolved in #4984

**Comment by sphuber** [comment] 2021-12-09 09:35
Not sure if we want to release a patch 1.6.6 with a backport or we leave it for now since `2.0` is around the corner. Once v2.0 is released we can close this for sure.

**Comment by sphuber** [comment] 2022-04-28 07:26
Closing this since v2.0 has been released

**Closed by sphuber** 2022-04-28 07:26 UTC
Labels: type/bug
