### ISSUE TITLE
Docs: Add QueryBuilder to Core Developers/AiiDA internals

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-core#3657] opened 2019-12-12 21:51 UTC
Talking with @lekah, I (hope) I have convinced him to contribute to, at minimum, a Q&A about the design ideas behind the `QueryBuilder` (QB) to the documentation (for developers).

The purpose of this is for future and current developers to more easily grasp the entirety and (historical) purpose of the QB, as well as why it handles things the way it does.

My hope is that the Q&A can pinpoint or sketch how the QB may be split up, e.g., making QB to a module, moving "boiler plate" code to a sub-module, leaving only what's additional in QB compared to its "wrapper" function around SQLA. Essentially making the QB code more approachable and transparent, so as to keep this excellent tool up-to-date with the rest of the code base.

**Comment by sphuber** [comment] 2020-10-14 08:58
This is a duplicate of #4041 and will be continued there.

**Closed by sphuber** 2020-10-14 08:58 UTC
Labels: topic/documentation, topic/query-builder
