### ISSUE TITLE
Docs: 404 on "Edit this page"

### ISSUE THREAD

**Issue by dev-zero** [aiidateam/aiida-core#4947] opened 2021-05-17 07:33 UTC
### Describe the current issue

1. open https://aiida.readthedocs.io/projects/aiida-core/en/latest/reference/apidoc/aiida.orm.html
2. click "Edit this page"
3. Get "404 page not found" from GitHub

### Describe the solution you'd like

Open an editor.

**Comment by ltalirz** [comment] 2021-05-18 12:49
Ok, I guess we may want to hide the button for the api docs... I guess this is "nice to have"

**Comment by MikeW1121** [comment] 2023-03-05 23:01
Hey, I was wondering how this should be approached. Are there any specifications on which editor it should open? And it's probably not the best for anyone to edit the documentation page right? Or should the button lead to the main Aiida GitHub page so people can fork and edit?

**Comment by ltalirz** [comment] 2023-03-05 23:04
Hey @MikeW1121 , the button works for "most" documentation pages - the problem is that the API documentation is auto-generated, and so the button does not make sense there.

I.e. one will need to find a way to hide the button on these pages.
@unkcpz marked this as a "good first issue", so perhaps he can point you in the right direction

**Comment by AhmedBasem20** [comment] 2023-03-16 00:10
Hi, I think we could hide that button for the API docs using CSS. We could write CSS code in .rst files using a raw directive.
I'll compile the documentation on my local machine first and if that solution worked I'll open a PR.

**Comment by Tezas-6174** [comment] 2023-03-26 20:54
Is this issue solved? If not, I'd like to work on it.

**Comment by ltalirz** [comment] 2023-03-26 23:25
I don't think it is - help welcome

**Comment by Tezas-6174** [comment] 2023-03-27 03:53
But, right now, only the 404-page task is done, which means it is partially solved. The `Edit this page` should open the editor, right?

**Comment by ltalirz** [comment] 2023-03-27 10:19
> the button works for "most" documentation pages - the problem is that the API documentation is auto-generated, and so the button does not make sense there.

> I.e. one will need to find a way to hide the button on these pages.

**Comment by Tezas-6174** [comment] 2023-03-27 22:00
Ok, so the hiding part is done in #5917. What next can be done?

**Comment by ltalirz** [comment] 2023-03-27 23:26
It isn't done. The PR was closed, not merged.
The button should only be hidden on the API documentation pages (more generally: pages that are autogenerated, and for which no corresponding document exists on the git repo)

**Closed** 2023-04-11 18:31 UTC
Labels: good first issue, priority/nice-to-have, topic/documentation
