### ISSUE TITLE
Passing pgtest arguments to test_manager does not work

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida-core#3482] opened 2019-10-30 08:53 UTC
We opened for the possibility to pass arguments to `pgtest` in #2941. Upon passing e.g.
`pgtest={'pg_ctl': '/usr/pgsql-9.6/bin/pg_ctl'}` as an argument to `test_manager` we now get:

```
self = <sqlalchemy.dialects.postgresql.psycopg2.PGDialect_psycopg2 object at 0x7fded9f91eb8>
cursor = <cursor object at 0x7fdeda2c49f8; closed: 0>
statement = 'SELECT db_dbcomputer_1.id AS db_dbcomputer_1_id, db_dbcomputer_1.uuid AS db_dbcomputer_1_uuid, db_dbcomputer_1.name A...uter_1_metadata \nFROM db_dbcomputer AS db_dbcomputer_1 \nWHERE db_dbcomputer_1.name = %(name_1)s \n LIMIT %(param_1)s'
parameters = {'name_1': 'localhost', 'param_1': 2}
context = <sqlalchemy.dialects.postgresql.psycopg2.PGExecutionContext_psycopg2 object at 0x7fded9f49048>

    def do_execute(self, cursor, statement, parameters, context=None):
>       cursor.execute(statement, parameters)
E       sqlalchemy.exc.OperationalError: (psycopg2.errors.AdminShutdown) terminating connection due to administrator command
E       server closed the connection unexpectedly
E               This probably means the server terminated abnormally
E               before or while processing the request.
E       
E       [SQL: SELECT db_dbcomputer_1.id AS db_dbcomputer_1_id, db_dbcomputer_1.uuid AS db_dbcomputer_1_uuid, db_dbcomputer_1.name AS db_dbcomputer_1_name, db_dbcomputer_1.hostname AS db_dbcomputer_1_hostname, db_dbcomputer_1.description AS db_dbcomputer_1_description, db_dbcomputer_1.scheduler_type AS db_dbcomputer_1_scheduler_type, db_dbcomputer_1.transport_type AS db_dbcomputer_1_transport_type, db_dbcomputer_1.metadata AS db_dbcomputer_1_metadata 
E       FROM db_dbcomputer AS db_dbcomputer_1 
E       WHERE db_dbcomputer_1.name = %(name_1)s 
E        LIMIT %(param_1)s]
E       [parameters: {'name_1': 'localhost', 'param_1': 2}]
E       (Background on this error at: http://sqlalche.me/e/e3q8)

../lib/python3.7/site-packages/sqlalchemy/engine/default.py:580: OperationalError
```

Previously this worked fine with `fixture_manager`.

**Comment by ltalirz** [comment] 2019-10-30 12:14
thanks for reporting - I'll have a look

**Comment by ltalirz** [comment] 2019-10-30 12:32
So, I can't really reproduce your issue - I can pass a `pgtest` argument with a path to an executable to `TestManager..create_aiida_db` and it works.

The error message somehow suggests that the issue happens further down the line.

I also noticed that you introduced the `pgtest` argument in https://github.com/aiidateam/aiida-core/pull/2941 without adding any tests.

I have two propositions: I will
 * add a test of this functionality
 * remove the `pgtest` argument from all functions of the `TestManager` except for the constructor (i.e. from `create_db_cluster`, `create_aiida_db` and `create_profile`) and rather use `self._pgtest` (if set).

**Comment by espenfl** [comment] 2019-10-30 12:41
Thanks for checking. #2941 was just to give an example. I have now closed that after realizing the best approach, as already suggested is to put this into some kind of config file.

**Comment by espenfl** [comment] 2019-10-30 12:43
Otherwise you suggestion sounds good and should also be compatible with a config file.

**Comment by ltalirz** [comment] 2019-10-30 12:45
> #2941 was just to give an example. 

I guess you confused this with the recent PR of yours. #2941 was merged (by seb) - it introduced the `pgtest` argument.

**Comment by espenfl** [comment] 2019-10-30 12:51
Indeed, sorry. Yes, no test was added in #2941. But it has been working fine with `fixture_manager` for some time.

**Comment by espenfl** [comment] 2019-10-30 13:08
In fact, there was an issue with the postgresql service. Not sure exactly why, but upon reset it is back to normal and I agree with you, passing `pgtest` in `test_manager` works. Closing this now.

**Closed** 2019-10-30 13:09 UTC

**Comment by ltalirz** [comment] 2019-10-30 13:16
Just saying that while trying to write a test for this, I'm running into a similar issue that seems to occur when trying to use a `TemporaryProfileManager` twice in the same test session.
This involves resetting the profile in the same session (which is unsafe and just for testing purposes).
 
This is the stacktrace:
```
Traceback (most recent call last):
  File "test_test_manager.py", line 114, in test_pgtest_argument
    self.test_manager.use_temporary_profile(backend=self.backend, pgtest=pgtest)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/manage/tests/__init__.py", line 88, in use_temporary_profile
    self._manager.create_profile()
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/manage/tests/__init__.py", line 332, in create_profile
    backend.migrate()
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/implementation/django/backend.py", line 53, in migrate
    migrate_database()
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/backends/djsite/utils.py", line 125, in migrate_database
    call_command('migrate')
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/migrations/loader.py", line 210, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/backends/base/introspection.py", line 55, in table_names
    return get_names(cursor)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/backends/base/introspection.py", line 50, in get_names
    return sorted(ti.name for ti in self.get_table_list(cursor)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/backends/postgresql/introspection.py", line 67, in get_table_list
    AND pg_catalog.pg_table_is_visible(c.oid)""")
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.OperationalError: terminating connection due to administrator command
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

**Comment by espenfl** [comment] 2019-10-30 18:46
Okey, nice to see you also encountered this. Yes, most likely I was running into this as I was playing with tests on the `aiida-vasp` side, but that is basically the same. Should we make a block for this, or eject a more sensible error message now that we can reproduce?

**Comment by ltalirz** [comment] 2019-10-30 20:21
Whether the problem I encountered is exactly the same as yours I don't know.
In my case, you are already blocked from running into this since the manager will fail with a sensible error message if you try to create a new profile the second time (`IntegrityError`).

I only manage to run into the issue if I use the (so far untested) `reset_profile()` function, which - apparently - does not yet reset enough state in the django backend. At least that is my guess as to why this error occurs.

Mentioning @sphuber just for info - I don't see need for action at the moment.
