### ISSUE TITLE
Able to delete computer with code associated

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#5700] opened 2022-10-16 12:46 UTC
### Is your feature request related to a problem? Please describe

We can now run `verdi code delete <code_pk>` even though the calculations are run by code and node associated with the code.
It will ask if to delete the nodes. 
When all the codes related to a computer are deleted, the computer can be deleted.
However, running `verdi computer delete <name>` for a computer has a code set (even if there are no other node connected with the code) will raise:

```
    CMDLINE_LOGGER.critical(message, extra=dict(nl=nl, err=err, prefix=prefix))
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 1493, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
  File "/opt/conda/lib/python3.8/site-packages/aiida/cmdline/utils/log.py", line 40, in emit
    self.handleError(record)
Message: '\x1b[22mUnable to delete the requested computer: it is possible that there is at least one node using this computer (original message: (psycopg2.errors.ForeignKeyViolation) update or delete on table "db_dbcomputer" violates foreign key constraint "fk_db_dbnode_dbcomputer_id_db_dbcomputer" on table "db_dbnode"\nDETAIL:  Key (id)=(2) is still referenced from table "db_dbnode".\n\n[SQL: DELETE FROM db_dbcomputer WHERE db_dbcomputer.id = %(id)s]\n[parameters: {\'id\': 2}]\n(Background on this error at: https://sqlalche.me/e/14/gkpj))\x1b[0m'
Arguments: ()
```

### Describe the solution you'd like

Similar to `verdi code delete`, it will ask to delete the code and nodes associated with the computer and delete the computer after no database node is connected.

**Comment by ltalirz** [comment] 2022-10-28 10:45
duplicate of https://github.com/aiidateam/aiida-core/issues/5395 ?

**Comment by ltalirz** [comment] 2022-10-28 10:45
closing as duplicate, feel free to reopen

**Closed by ltalirz** 2022-10-28 10:45 UTC
Labels: type/feature request
