### ISSUE TITLE
Do not use `Profile.repository_uri` as the location for sandbox creation

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#5494] opened 2022-04-23 19:09 UTC
The `repository_uri` key in a profile configuration is used for two purposes. It is the base path for both the repository container, but also for the directory where `SandBoxFolder`s are created. Really this key should only be used for the location of the repository. The location of the sandbox folders should simply be in the tmp folder of the operating system. This decoupling will make it possible to introduce storage backends in the future that do not have a path on the local file system for a file repository.

**Comment by chrisjsewell** [comment] 2022-05-04 12:03
this is a duplicate of #5353

**Closed** 2022-05-13 13:18 UTC
Labels: topic/config, priority/nice-to-have, type/refactoring
