### ISSUE TITLE
kill the parent workchain does not kill its child process 

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#4298] opened 2020-08-12 09:59 UTC
### Steps to reproduce

1. running the following script
```python
from aiida.plugins import CalculationFactory, WorkflowFactory
from aiida.engine import run


MultiplyAddWorkChain = WorkflowFactory('arithmetic.multiply_add')

code = load_code(label='add@localhost')
inputs = {
    'x': Int(1),
    'y': Int(2),
    'z': Int(3),
    'code': code,
}

# Normal inputs should run just fine
results, node = run.get_node(MultiplyAddWorkChain, **inputs)
```
2. Before it finished terminate the process by `Ctrl+c`
3. See error: the child process `ArithmeticAddCalculation` is in waiting and unreachable.

### Your environment

- Operating system [e.g. Linux]:
- Python version [e.g. 3.8.1]:
- aiida-core version [e.g. 1.3.0]:

Other relevant software versions, e.g. Postres & RabbitMQ

**Comment by sphuber** [comment] 2020-08-12 12:08
This is a duplicate of #3776 but we can keep this around as it gives an actual example to reproduce it.

**Comment by unkcpz** [comment] 2020-10-20 09:50
More information about this issue. 
1) If use submit to launch the workchain, and kill the parent process, the child process is able to be killed. 
2) Before the parent process kill the child by `controller.kill_process(child.pk, 'msg')` in `aiida.engine.processes.process` the child process is unreachable. `controller.kill_process` return the exception `kiwipy.exceptions.UnroutableError: ('NO_ROUTE', '[rpc].102')`

**Comment by ltalirz** [comment] 2021-01-22 13:49
> 2\. See error: the child process `ArithmeticAddCalculation` is in waiting and unreachable.

@unkcpz Could you please elaborate a bit on this - which error?


I just tried reproducing this issue on aiida-core v1.5.2 and depending on when I abort, I either get
```
$ verdi run runtest.py
^C
Aborted!
```
or
```
$ verdi run runtest.py
^CTraceback (most recent call last):
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/bin/verdi", line 12, in <module>
    sys.exit(verdi())
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/cmdline/utils/decorators.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/cmdline/commands/cmd_run.py", line 147, in run
    exec(compile(handle.read(), scriptname, 'exec', dont_inherit=True), globals_dict)  # yapf: disable # pylint: disable=exec-used
  File "runtest.py", line 16, in <module>
    results, node = run.get_node(MultiplyAddWorkChain, **inputs)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/engine/launch.py", line 59, in run_get_node
    return runner.run_get_node(process, *args, **inputs)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/engine/runners.py", line 262, in run_get_node
    result, node = self._run(process, *args, **inputs)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/engine/runners.py", line 238, in _run
    process.execute()
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.6/site-packages/plumpy/processes.py", line 85, in func_wrapper
    return func(self, *args, **kwargs)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.6/site-packages/plumpy/processes.py", line 1071, in execute
    return self.future().result()
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.6/site-packages/plumpy/futures.py", line 32, in result
    return super().result(timeout)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
plumpy.exceptions.KilledError: Process was killed because the runner received an interrupt
```

**Comment by unkcpz** [comment] 2021-01-23 03:49
>  Could you please elaborate a bit on this - which error?

@ltalirz When you check the process list you can find the parent workflow is killed but the child one is left in the list and unreachable.

**Comment by chrisjsewell** [comment] 2021-01-26 16:34
> This is a duplicate of #3776 but we can keep this around as it gives an actual example to reproduce it.

I'm closing this, because its not helpful to have the same conversation in two issues, and I have now a more reproducible method to study this: https://github.com/aiidateam/aiida-core/issues/3776#issuecomment-767663801

**Closed by chrisjsewell** 2021-01-26 16:34 UTC
Labels: topic/engine, topic/processes, topic/workflows, type/bug
