### ISSUE TITLE
memory consumption during `verdi import`

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3936] opened 2020-04-15 16:20 UTC
It seems that the current implementation of the `verdi import` makes very inefficient use of memory, even given the constraints of the export file format (https://github.com/aiidateam/aiida-core/issues/493).

For example, take [this export file](https://archive.materialscloud.org/record/file?record_id=349&file_id=8b48ebc7-8c9e-4d87-b22d-b1fd7989434a&filename=Sb2Te3_slab_imp_scf_nodes.tar.gz):

zipped: 14 GBytes

extracted:
* data.json: 1.4 GByte
* metadata.json: 3.7 MByte
* nodes (file repo): 22 GByte

Given the constraints of the export format, the `data.json` file needs to be read into memory in one go and parsed, so I would be fine with a memory usage of perhaps ~3 GBytes.
In any case, importing this file should pose no problem on a machine with 16 GByte memory.

Test with aiida-core 1.1.1:
Memory usage starts around 300 MB reserved memory during file extraction.
While `EXTRACTING NODE DATA` is still shown, the reserved memory rises sharply to ~11 GB
During `UPDATING EXISTING NODE EXTRAS`: 9G -13 G
During `STORING NODE LINKS`: 9G
During `STORING GROUP ELEMENTS`: rises up to full available memory (~14GB) and is killed

Mentioning @giovannipizzi for info

**Comment by CasperWA** [comment] 2020-04-15 16:29
Just to be sure, this is tested with the current setup and not on my branch for #3599?

**Comment by sphuber** [comment] 2020-04-15 16:35
Just a note that this is a duplicate of #493 (and probably a few others). Fine to close that one and continue here, just that we do not create many issues for the same problem.

**Comment by ltalirz** [comment] 2020-04-15 16:46
> Just a note that this is a duplicate of #493 (and probably a few others). Fine to close that one and continue here, just that we do not create many issues for the same problem.

This is not a duplicate - please read ;-)

**Comment by ltalirz** [comment] 2020-04-15 16:47
> Just to be sure, this is tested with the current setup and not on my branch for #3599? 

Yes, this is tested with aiida-core 1.1.1

**Comment by ltalirz** [comment] 2020-04-15 17:18
@CasperWA Thanks for the hint - I tested it now with your branch as well and it turns out your optimizations were enough to get this one through :-)

It should still be possible to bring down memory usage significantly, though.
E.g. reserved memory of the process was
`Generating list of data`: 5 G -9 G
...
`Creating import group`: 11.8 G

The fact that the peak is at the end suggests to me that the issue could be duplication of data lying around in variables (lists, dictionaries, ...) that perhaps could just be freed (or duplication reduced).

**Comment by sphuber** [comment] 2020-04-15 17:22
> This is not a duplicate - please read ;-)
> #493 is about the built-in limitation of the export format, which requires the `data.json` to be fully

Apologies, I missed that you already linked it. Just a suggestion that it might be useful to maybe create one single master issue or project where we collect the various issues related to memory in the import. This would probably make it easier to organize any solution than to have multiple scattered issues. Other related issues:
#3712 
#3575 
#999 
#493

**Comment by ltalirz** [comment] 2020-04-15 17:44
@sphuber Agreed, I think we should use the import/export project for this https://github.com/aiidateam/aiida-core/projects/5

I've now
 * moved the new issues to the project
 * closed #999 , which was just an "always on" tracking issue
 * updated the title of #493  to clarify its scope (was already tracked in the project)

**Comment by ltalirz** [comment] 2020-10-29 23:14
@chrisjsewell I just retested memory usage during import of the file linked above and the resident set size of the process still shoots up to ~11GB:

![image](https://user-images.githubusercontent.com/1053245/97641872-35f0bd80-1a44-11eb-9671-654ac8409582.png)

As mentioned above, this is for a `data.json` of only 1.4GByte. Do you have an idea why?

**Comment by chrisjsewell** [comment] 2020-11-04 14:53
possibly, as we have seen with migration, there may be essentially multiple versions of data.json being held in memory at the same time.
Anyhow, I/we will look at this in the import refactor take 2 (coming soon)

**Comment by giovannipizzi** [comment] 2020-11-11 14:12
One thing to check is at which timestamp the commit to the DB takes place.
Most probably the very last peak is due to postgres and not our code. Not sure about the big peak at the centre (probably our code as @chrisjsewell says

**Closed** 2021-12-01 05:58 UTC
Labels: priority/important, topic/archive, type/performance
