### ISSUE TITLE
`verdi daemon start` claims to fail but, in fact, is successful. 

### ISSUE THREAD

**Issue by ConradJohnston** [aiidateam/aiida-core#3800] opened 2020-02-24 16:11 UTC
Like a miserable aggressively-humble inhabitant of the UK and Ireland, `verdi daemon start` claims failure while actually being successful.

When starting the daemon on my system, it reliably `fails` the first time, every time.
Running `verdi daemon start` a second time after a failure works as expected.
This a fresh install of v1.1.0.

If one monitors `ps -e | grep verdi` directly after a failure,  the following process is spawned: 
```
59170 ??         0:00.04 /Users/conrad/.virtualenvs/aiidapy/bin/python3.7 /Users/conrad/.virtualenvs/aiidapy/bin/verdi -p Testing daemon start-circus 1
```
If one waits a moment and then searches the processes again, the following is also shown:
```
59189 ??         0:01.08 /Users/conrad/.virtualenvs/aiidapy/bin/python3.7 /Users/conrad/.virtualenvs/aiidapy/bin/verdi -p Testing devel run_daemon
```

Seemingly the check for success is happening before the daemon worker has a chance to spin up and so fails spuriously.

**Comment by sphuber** [comment] 2020-04-14 06:37
Have you experienced this since @ConradJohnston ? Is this a regular occurrence and/or can you make it happen deterministically? If so it would be good to try and add an additional printing line in the command itself to print the full output based on which we say whether the starting of the daemon was successful or failed. This should be in `aiida.cmdline.commands.cmd_daemon:start`. We call a subprocess and if that raises, we print `[FAILED]`. It would be good to also print the full stack trace in that case.

**Comment by hongyi-zhao** [comment] 2020-04-14 06:50
also see [here](https://groups.google.com/forum/#!topic/aiidausers/sRQoSEgGdQ0)

**Comment by ltalirz** [comment] 2020-04-14 08:22
@hongyi-zhao Since you encountered this issue as well, it would be great if you could help pin down the source of the error.

E.g. replace this line
https://github.com/aiidateam/aiida-core/blob/67ae49f37055eaa69aa22c61afdf7802b09e73f3/aiida/cmdline/commands/cmd_daemon.py#L67
by
```python
import traceback
echo.echo_critical(traceback.format_exc())
```

**Comment by hongyi-zhao** [comment] 2020-04-14 08:55
@ltalirz Thanks, done it. I'll see and feedback.

**Comment by ltalirz** [comment] 2022-09-07 12:58
Just mentioning that we recently encountered an issue, where `verdi daemon restart` would time out, while (after a couple of seconds) the daemon would actually restart successfully.

In this particular example we _know_ that the command run by the daemon worker was stuck (it was waiting for input). I.e. it may be that the timeout on the `verdi daemon restart` side may be shorter than (or equal to) the timeout related to the killing of the daemon worker process.
Discussed this with @sphuber, who may have a look into this when he finds time.

**Comment by sphuber** [comment] 2022-09-08 07:21
I cannot reproduce it (neither for `verdi daemon start` nor `verdi daemon restart`), but looked at the code and the two phenomena are not necessarily the same. For the `verdi daemon start` case, it launches `verdi daemon start-circus` in a subprocess and if that returns a non-zero exit status, the `FAILED` is printed. However, for `verdi daemon restart`, the circus daemon is already running and we send a signal to it through the `CircusClient` asking it to restart the workers. The client call has a timeout, which is what was being observed in the case mentioned by @ltalirz .

**Comment by ltalirz** [comment] 2023-01-03 14:49
Just encountered another case of `verdi daemon start` returning `FAILED` (but actually starting the daemon successfully).
I'm not able to reproduce it, unfortunately.

I also notice that, in a setup where the .aiida directory is shared between machines, trying to start the daemon on one machine, while another machine is already running the daemon, results in a different error message:
```
$ verdi daemon start
Starting the daemon with 1 workers... Critical: stopped
```
(without any further explanation).

**Comment by mbercx** [comment] 2023-11-15 21:01
Just adding this here, since the issue is similar. With `aiida-core==2.4.1` I'm running into the following:

```
❯ verdi daemon restart --reset --timeout 20
Profile: dev
Stopping the daemon... OK
Starting the daemon with 1 workers... FAILED
Critical: The daemon failed to start or is unresponsive after 2 seconds.
```

The message is pretty clear that it's also possible that the daemon started but is simply unresponsive, but I would expect that it waits for 20 seconds due to the `--timeout` setting

```
  -t, --timeout INTEGER           Time in seconds to wait for a response
                                  before timing out.
```

I then configured the default `timeout` to 20 seconds and all was well:

```
❯ verdi config set daemon.timeout 20
Success: 'daemon.timeout' set to 20 for 'dev' profile
❯ verdi daemon restart --reset
Profile: dev
Stopping the daemon... OK
Starting the daemon with 1 workers... OK
```

So two suggested action points would be:

1. Fix the `--timeout` not being used properly, unless I misunderstand it's purpose?
2. Increase the default timeout to e.g. 5 or 10.

**Comment by sphuber** [comment] 2023-11-16 08:07
Thanks @mbercx . Since this is a different issue, could you please open a new issue for this. The daemon has been refactored significantly since the original issue and I am not sure it applies any longer, so I will be closing this one

**Closed by sphuber** 2023-11-16 08:07 UTC
Labels: type/bug, topic/daemon, topic/verdi, priority/nice-to-have
