### ISSUE TITLE
calcjob test failure with sqlite backend

### ISSUE THREAD

**Issue by danielhollas** [aiidateam/aiida-core#6386] opened 2024-05-10 00:53 UTC
I was trying to run the test suite using a profile setup with verdi presto, i.e. sqlite backend and no broker.
The only thing needed make this work was to comment auto the redefined `aiida_profile` fixture in `tests/conftest`.

Obviously many tests fail in this setup as they either require rabbitMQ or PSQL backend. But one test failure caught my attention as rather suspicious as it is not clear to me why it should fail, specifically test `cmdline/commands/test_calcjob.py::TestVerdiCalculation::test_calcjob_cleanworkdir`

```pytest
    def test_calcjob_cleanworkdir(self):
        """Test verdi calcjob cleanworkdir"""
        # Specifying no filtering options and no explicit calcjobs should exit with non-zero status
        options = []
        result = self.cli_runner.invoke(command.calcjob_cleanworkdir, options)
        assert result.exception is not None
    
        # Without the force flag it should fail
        options = [str(self.result_job.uuid)]
        result = self.cli_runner.invoke(command.calcjob_cleanworkdir, options)
        assert result.exception is not None
    
        # With force flag we should find one calcjob
        options = ['-f', str(self.result_job.uuid)]
        result = self.cli_runner.invoke(command.calcjob_cleanworkdir, options)
        assert result.exception is None, result.output
    
        # Do it again should fail as the calcjob has been cleaned
        options = ['-f', str(self.result_job.uuid)]
        result = self.cli_runner.invoke(command.calcjob_cleanworkdir, options)
>       assert result.exception is not None, result.output
E       AssertionError: Success: 1 remote folders cleaned on localhost
E         
E       assert None is not None
E        +  where None = <Result okay>.exception
```

The failure suggest that cleaning a working directory of a calcjob does not work as expected?

**Comment by sphuber** [comment] 2024-05-21 20:59
Closing as duplicate of #6256

**Closed by sphuber** 2024-05-21 20:59 UTC
Labels: type/bug

**Comment by sphuber** [comment] 2024-05-21 21:37
That would perhaps be a necessary stop-gap solution until it can be implemented for sqlite, if ever. Let's discuss that in #6256
