### ISSUE TITLE
Docs: flow of Introduction section unclear

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#4254] opened 2020-07-11 10:06 UTC
### Describe the current issue

The 2020 virtual tutorial left a number of participants confused about the flow of the "Introduction" section.

In particular:
 * For some people taking the conda route, it was unclear that they needed to initialize the database and start the postgres server manually (+rabbitmq)
 * For some people taking the "system postgresql/rabbitmq" route it was unclear that they do *not* need to manually create a database and start the postgres server (+rabbitmq)
 * Some people taking the conda route ended up in the "detailed installation" section and trying things, while their installation was already ready to go

### Describe the solution you'd like

Looking back at the Introduction section, I see two possible sources of this confusion:

1) The 4 choices at the beginning of the "Getting started" section have blue buttons that send you directly to parts of the "detailed instructions". Many users probably clicked on them and therefore simply jumped over the "Quick start" section.

My proposed solution:
Move the 4 choices to the end of the "Getting started" section and begin with the "Quick start" right away (if you like, we can leave a link to "alternative ways of installing AiiDA" in the beginning of "Getting started").

2) The current layout suggests a sequential structure, where the "detailed instructions" come after the "getting started". In my opinion, after "Getting started" the "Basic tutorial" should be next.
![image](https://user-images.githubusercontent.com/1053245/87144095-854d8b00-c2a7-11ea-9b53-e50139eb7ff4.png)
  
My proposed solution: Move the detailed installation towards the end of the "Introduction" section

What is AiiDA
Getting started
Basic tutorial
Troubleshooting
Detailed installation

Mentioning @chrisjsewell @mbercx @giovannipizzi 

P.S. I have no strong opinion on the order of Troubleshooting vs Detailed installation; swapping them around would also be fine.

**Comment by chrisjsewell** [comment] 2020-07-11 12:10
Thanks @ltalirz. Hmm, its difficult, I don't have a clear solution. Me and @csadorf went over this before and I get the impression that everyone is going to have a different opinion on this, and it's always going to confuse at least one person. Although I agree there is room for improvement I would note:

> For some people taking the conda route, it was unclear that they needed to initialize the database and start the postgres server manually (+rabbitmq)

The section headings in the quick start are literally:

- Install Software
- Initialise Data Storage
- Start Computation Services

How much more clear can you be lol?

> For some people taking the "system postgresql/rabbitmq" route it was unclear that they do not need to manually create a database and start the postgres server (+rabbitmq)

Yes I think this needs to be clearer

> alternative ways of installing AiiDA... Move the detailed installation towards the end

I guess the problem there is that then very heavily implies that people should use the conda installation route over others, which is not to everyone's taste. Something like this would be good to note (adapted from the slack I think was @ltalirz or @CasperWA)

 There are two options:
1) use postgresql & rabbitmq from your operating system
this has the advantage that it is integrated into startup etc (no need to worry what to do when you restart your computer)
2) install the postgresql & rabbitmq binaries through conda
this has advantages for development, since this works the same on macos, linux and windows
+ the postgresql & rabbitmq binaries will be the same for anyone running the command, i.e. you can tightly control what versions are installed and where data is stored.
However, with option 2) you will need to take care of starting postgresql & rabbitmq yourself

**Comment by chrisjsewell** [comment] 2020-07-11 14:45
Not to get into a flame war over conda vs venv/pip lol. But I also want to mention the reason that I much prefer to use conda environments and installs where possible (unfortunately they are obviously not available for all packages), is that it is much better and clearer at handling version dependencies, particularly those with c-bindings like numpy. Literally in a bunch of our own CI tests we have to pre-install numpy to address pip shortcomings:  https://github.com/aiidateam/aiida-core/blob/9636ac773f8e92da6f7a8e882e469576ba9c1ce3/.github/workflows/ci.yml#L28 (we also address this in [the troubleshooting section](https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/troubleshooting.html#numpy-dependency).

Also, pip installing into an existing environment has the potential to really mess things up. I encountered this recently with the aiidalab install into the Quantum Mobile VM, which introduced a bunch of version clashes without much warning. At the very least it should be recommended that people run `pip check` after they install new packages (e.g. plugins) into their environment.

**Comment by astamminger** [comment] 2020-07-11 16:13
> But I also want to mention the reason that I much prefer to use conda Environments and installs where possible

Amen

**Comment by ltalirz** [comment] 2020-07-11 21:38
> Something like this would be good to note (adapted from the slack 

Yes, I agree that the distinction between system vs user-controlled services should be made more prominent.

I'll think a bit more about this and try to come up with a PR some time next week.
I think one needs to kind of see the end result here to make a judgement.

**Comment by csadorf** [comment] 2020-07-13 13:42
In my opinion, we should revise the installation section based on the following principles:

1. There should be a very clear *single preferred path* that is optimal for the majority of users.
This path should be *installation via conda* and I think it is relatively easy to make that case without needing to resort to personal taste.
2. We still provide alternative installation methods for everyone who **cannot** or **does not want to** use the preferred path. Choosing these alternative paths is perfectly justified under specific conditions, however – by definition – will be only suitable for specific environments, come with drawbacks, and may potentially require additional steps.

I propose the following concrete changes (some of which I advocated for previously):

1. Replace "Direct (Bare metal)" with "Install with conda/pip" and link to the lower section of the page. This panel should be clearly marked as "preferred" both in text and visually.
1. Remove "Virtual Environment".†
1. Add mybinder as 2nd option and clearly mark as *testing playground*. ‡
1. Clearly mark the "conda" panel as part of the "conda/pip" panels as preferred both in text and visually.
1. Move all instructions concerning the installation of required services into a separate top-level intro section: "Installation of services". This section should contain the conda instructions for services (minor duplication), and otherwise primarily and almost exclusively information on *what* services must be installed, with a few links to the more specific instructions. There should be no detailed information on how to install these services otherwise, because it is not our responsibility to provide duplicated or even better instructions on how to install services than the services developers themselves.
1. Restructure the remainder of the "Detailed Installation" section into the paths previously introduced : conda, pip, mybinder, docker, VM. The pip path will link to the "Installation of services" section.
1. Move "Using AiiDA in Jupyter" section from "Detailed Installation" into a separate top-level section as part of intro or how-to's.
1. Move all detailed instructions concerning database setup into an intro: "Custom profile setup" (or similar) top-level section.

†) Whether a user installs aiida-core into their root environment or into a virtual environment (conda or not) is irrelevant in this context. 
‡) There should now be exactly 4 primary paths: conda/pip, mybinder, docker, VM, where the first one (conda/pip) is split as it is right now.

@ltalirz I've assigned myself to this issue as well, however please feel free to take a stab at this first. However, when you do, I would appreciate if you could take my recommendations into account.

As an aside, these kinds of comments are not constructive and are a not user-oriented:

> How much more clear can you be lol?

If there are multiple users having trouble finding the right path then it is simply not clear enough. This is a problem with the documentation, not with the users.

**Comment by ltalirz** [comment] 2020-07-13 14:15
@csadorf Thanks a lot for your suggestions!
I agree with basically all of them and since I have to work on a couple of other things at the moment, I'd be happy of you could prepare a version following your suggestions and we can iterate on it.

I just wanted to reiterate two points I made, which I think would be compatible with your proposal:

 * While I get the purpose of showing the 4 possible options at the beginning, this is a bit "dangerous" since it invites people to click on the blue buttons and jump away from the intended flow. I think it would also be ok to just focus on the default route in the beginning and link to the place (further down) where the 4 options have moved.

 * I would move the "detailed instructions" (or whatever is left over from it) *after* the basic tutorial in order to move them out of the sequential structure that people typically follow.

**Comment by chrisjsewell** [comment] 2020-07-13 14:44
> single preferred path... This path should be installation via conda

If we actually want this to be the case, then we should be using "Install with conda" not "Install with conda/pip", installing with conda and pip are **not** the same route, they are two distinct options: one (pip) that involves an aspect of bare metal/system wide installation (of postgres & rabbitmq) the other (conda) that is entirely an encapsulated environment.

> Add mybinder as 2nd option

I guess we need to actually implement this first 😄 As a reminder I've recently implemented this for the aiida-tutorial (https://github.com/aiidateam/aiida-tutorials/pull/231, which I'll re-open when I have time)

I would note that this option is essentially the same as docker, just running the docker container via the web rather than locally. So it does not exactly fit with my original intention for the panels to demonstrate an increasing level of virtualisation: bare metal/system wide installs -> venv like folder encapsulation -> container based virtualization -> full virtual machine.

> As an aside, these kinds of comments are not constructive and are a not user-oriented

I disagree, I think it's perfectly legitimate to point out in response to "it was unclear that they do not need to manually create a database" to point out that this is specifically stated in the text: "Before working with AiiDA, you must first initialize a database storage area on disk.".
If there is clear evidence of users having issues with the instructions/wording, sure we can change it, but if there is no specific indication of why it was unclear, then I am not inclined to re-think it.

> jump away from the intended flow ... link to the place (further down) where the alternative options would be moved.

Yep I can see the logic in that 👍 

Also note, an outcome from the tutorial is that there was some thinking to refine [my live zoom tutorial](https://epfl.zoom.us/rec/play/7pcvdu37rWo3GNHH5ASDVPMsW9W7fKOshCEc-6cFnRuzW3cHZFX0b7sVYeQXjsx1YuAS-bqbNIFAA8vn?autoplay=true&startTime=1594399516000)* into a standalone tutorial, similar to [my tutorial on Quantum Mobile](https://www.youtube.com/watch?v=vlmjVwGJgEU&list=PL19kfLn4sO_-e_A9lVYb_NBNcwoVvUP6V&index=4); then perhaps both (after removing tutorial specific details and my ugly mug lol) could actually be embedded or linked to in the documentation.

* hopefully you have access to that?

**Comment by csadorf** [comment] 2020-07-13 16:07
> I agree with basically all of them and since I have to work on a couple of other things at the moment, I'd be happy if you could prepare a version following your suggestions and we can iterate on it.

I will give it a shot.

> 
> I just wanted to reiterate two points I made, which I think would be compatible with your proposal:
> 
>     * While I get the purpose of showing the 4 possible options at the beginning, this is a bit "dangerous" since it invites people to click on the blue buttons and jump away from the intended flow. I think it would also be ok to just focus on the default route in the beginning and link to the place (further down) where the alternative options would be moved.
> 

I see two alternatives:

1. We keep the current order and make sure that the default route is clearly visually distinguished.
2. We move the alternative routes to the bottom, but add a link to them right below the first two panels.

I suggest we try both and then re-evaluate.

>     * I would move the "detailed instructions" (or whatever will be left over from it) _after_ the basic tutorial in order to move them out of the sequential structure that people typically follow.

Agreed.

> > single preferred path... This path should be installation via conda
> 
> If we actually want this to be the case, then we should be using "Install with conda" not "Install with conda/pip", installing with conda and pip are **not** the same route, they are two distinct options: one (pip) that involves an aspect of bare metal/system wide installation (of postgres & rabbitmq) the other (conda) that is entirely an encapsulated environment.
> 

The recommended single path is conda: you get there by clicking on conda/pip and then following the conda instructions. The pip-path requires additional steps that we can link to. This flow acknowledges that installation with conda and pip are on a very similar level virtualization-wise†, share a lot of steps after installing the core package and services, and are generally more similar to each other than to the other methods.

†) You could absolutely install services into the user space when you take the pip route. The fact that we are currently providing instructions for installing services into root space is a limitation that I would like to remove anyways. Installation of services into the root space is an option and can be convenient, but it's not the only way.

The alternative is that we remove pip from the "quick start" flow and have that exclusively as part of the "detailed instructions". I personally do not think that is necessary or preferable, but it might work better, not sure.

> > Add mybinder as 2nd option
> 
> I guess we need to actually implement this first 😄 As a reminder I've recently implemented this for the aiida-tutorial ([aiidateam/aiida-tutorials#231](https://github.com/aiidateam/aiida-tutorials/pull/231), which I'll re-open when I have time)

We could try to leave it as homework for later, but then we're left with 3 panels...

> I would note that this option is essentially the same as docker, just running the docker container via the web rather than locally. So it does not exactly fit with my original intention for the panels to demonstrate an increasing level of virtualisation: bare metal/system wide installs -> venv like folder encapsulation -> container based virtualization -> full virtual machine.

We could add the mybinder link to the docker panel if it is truly equivalent.

I think your interpretation of virtualization is exactly where our difference in opinion on this originates. As argued above, I consider pip+conda to be on the exact same level virtualization wise. I don't think that installing aiida-core system-wide (i.e. with `sudo pip install ...`) even as an option... But it is not our responsibility to educate users on that, we show how to install aiida-core with pip, that's it.

> > As an aside, these kinds of comments are not constructive and are a not user-oriented
> 
> I disagree, I think it's perfectly legitimate to point out in response to "it was unclear that they do not need to manually create a database" that this is specifically stated in the text: "Before working with AiiDA, you must first initialize a database storage area on disk.".
> If there is clear evidence of users having issues with the instructions/wording, sure we can change it, but if there is no specific indication of why it was unclear, then I am not inclined to re-think it.

According to @ltalirz 's issue description multiple users had issues with the flow, which is evidence enough to me that there is room for improvement. Furthermore, I find reacting with "lol" to user issues generally inappropriate.

> > jump away from the intended flow ... link to the place (further down) where the alternative options would be moved.
> 
> Yep I can see the logic in that 👍
> 
> Also note, an outcome from the tutorial is that there was some thinking to refine [my live zoom tutorial](https://epfl.zoom.us/rec/play/7pcvdu37rWo3GNHH5ASDVPMsW9W7fKOshCEc-6cFnRuzW3cHZFX0b7sVYeQXjsx1YuAS-bqbNIFAA8vn?autoplay=true&startTime=1594399516000)* into a standalone tutorial, similar to [my tutorial on Quantum Mobile](https://www.youtube.com/watch?v=vlmjVwGJgEU&list=PL19kfLn4sO_-e_A9lVYb_NBNcwoVvUP6V&index=4); then perhaps both (after removing tutorial specific details and my ugly mug lol) could actually be embedded or linked to in the documentation.
> 
>     * hopefully you have access to that?

Not sure if that question was directed at me, but I do have access to that. I think a video could be a nice supplement to our documentation, but is of course a bit harder to maintain in case that we want to revise the flow.

**Comment by chrisjsewell** [comment] 2020-07-13 16:43
> The pip-path requires additional steps that we can link to

But this then lands them in the detailed section, which is what @ltalirz was arguing against?
If we absolutely don't want this to be the case, then I'd argue we should remove the link to installing pre-requisites.

![image](https://user-images.githubusercontent.com/2997570/87327883-95c26780-c52c-11ea-9f27-a9ee6c6d2811.png)

> I consider pip+conda to be on the exact same level virtualization wise.

Yep we'll agree to disagree 😄  because I do quite disagree with this belief; they are two distinctly different beasts and I think it may confuse newcomers to group them together without more explanation of their differences (as mentioned before [this is an interesting read](https://jakevdp.github.io/blog/2016/08/25/conda-myths-and-misconceptions))

>  which is evidence enough to me that there is room for improvement.

I will be interested to see your improvements 😉 

> Furthermore, I find reacting with "lol" to user issues generally inappropriate.

Just to clarify, I would never directly reply to a user like this (just to hypothetical users lol). Also the lol was intended to soften the abrasive question, not to actually laugh at the user, but I can understand how this could be misinterpreted as such.

**Comment by giovannipizzi** [comment] 2020-07-19 13:32
Hi all,
thanks for all your comments on the thread.

I in general agree with the direction in which you are going. Just a comment:
> There should be a very clear single preferred path that is optimal for the majority of users.
This path should be installation via conda and I think it is relatively easy to make that case without needing to resort to personal taste.

While I agree it's better to have a single path to suggest, I have just a reservation on this: I see one major issue (maybe the only one) with Conda, that at every reboot you have to restart the services by hand. Since users install AiiDA, read the instructions, but then maybe reboot a few weeks later, they might have forgotten and get confused. Maybe this is still acceptable overall as a compromise with installation simplicity. But what about starting at the very beginning with two bullet points that say that there are two methods, one with Conda (but the "con" is that at every reboot you have to start the services), and one with "pip", for which we also provide a page, saying that then it's up to them to integrate with system services (RabbitMQ, PostgreSQL) so a bit more complex, but services might restart at every reboot? We can also suggest explicitly that if they don't know which route to take, then they should continue with the Conda one, that would be the one coming just next (and pip is in a different page, just linked).

Also, if we manage to catch the common errors (e.g. in `verdi`?) when the DB and/or RMQ are down, and we add a message to the exception saying clearly something like "you might have your DB shut down, please turn it on, for more instructions see http://...", maybe this solves completely the issue.

Regarding the panels, I also think that now we don't indicate a clear path to follow, so it would be better (as suggested above) to be very clear on what people should follow, and what is the suggested one.
Now, as a 'default' user, what I do when I am [here](https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/get_started.html) is to 
1. read quickly, miss the sentence `There are multiple routes to setting up a working AiiDA environment. These are shown below, followed by a recommended “quick-install” route on your local computer.` because my attention is directed to the colourful panels (as it should! This is the goal of the panels).
2. Assume panels are sorted by "suggested method", so pick the first
3. try to click on the panel -> it does not work
4. try to click on the title of the panel -> it does not work
5. click on the first of the blue buttons ("Prerequisites install"), follow from there -> I am now in the "Detailed installation" section, and I will never go back to the suggested quick setup

This above is what I really did myself, and I am quite convinced is many people in practice would do. So I'm in favour of streamlining the process considering how most users behave when they see the page. I think the suggestion above are good, and we can check once a PR is ready.

One good test, before merging, would be to do what is typically done when optimising user experience of a GUI or a webpage: take one/two 'random', non expert user in the group, and ask to install AiiDA giving just the link to the docs. Ask the to explain what they are doing and why, and collect the info (essentially, collect the 5 bullet points above).
Improve if needed (e.g. for the points above: 1) make sure the attention is directed to what we want them to see first; 2) make sure panels are in order of preference for those who don't understand the difference from the title (there is a lot of technical jargon and many users would have no clue if "Bare metal" is better than a "Virtual Environment", a "Container" or a "Virtual Machine" (many will hear those words here for the first time); 3 and 4) -> should the titles be clickable? 5) make sure the 'default' path brings them to the quick setup as we want, and make sure we don't skip things that are essential just to make the guide shorter.

As a final setup (partially a consequence to my comment to 5) in the previous line): 
if we want `conda` to be the default, now if I follow the quick start, the only thing I see is that I have to type
```
conda create -n aiida -c conda-forge aiida-core=1.3.0 aiida-core.services=1.3.0
conda activate aiida
reentry scan
```
I do it on my PC and I get:
```
conda: command not found
```
I think here we lose a lot of users. We should have a link that says clearly that you have to install Conda first. Also, the current link goes to the Conda docs, but the installation instructions for Conda are not in that page, we should probably link directly to the Conda installation page.

Also there, here where I think we lose another % of users (well, here you almost lost me ;-) ):
https://docs.conda.io/projects/conda/en/latest/user-guide/install/macos.html
Here there are already two paths: `anaconda` and `miniconda`. Which should I choose? Is one better than the other? If I click on a few links I read things like "Miniconda is a free minimal installer for conda. It is a small, bootstrap version of Anaconda [...]". But is this enough for AiiDA?

I think it's our responsibility to have a preliminary paragraph that says:
- we suggest conda
- you need to install Conda first
- this is the installation page, if unsure/you don't know Conda, please pick Anaconda (or miniconda, whatever we want users to get)
- come back here and follow the next three lines

(Consider this above as me acting as the 'random' user I mentioned before ;-) - if you get at least another person that gets confused like me - I am still not sure of what I picked between the two, and if I did the right choice - I think it means we need to make the section more clear).

**Comment by csadorf** [comment] 2020-07-21 13:26
> While I agree it's better to have a single path to suggest, I have just a reservation on this: I see one major issue (maybe the only one) with Conda, that at every reboot you have to restart the services by hand. Since users install AiiDA, read the instructions, but then maybe reboot a few weeks later, they might have forgotten and get confused.

@giovannipizzi I read all of your comment and mostly agree, however this one paragraph I have an issue with and it similar to what I already wrote to @chrisjsewell : We need clearly to distinguish the issue of installing services from whether you are installing AiiDA with pip or conda. While it is true, that we can't install the services via pip, just because you use conda does not mean that you *have* to install the services with conda. Quite the opposite. The same goes for pip: just because you use pip does not mean you *have* to install the services as system services, you could install them in user space just as well (just not with pip).

So I think, trying to better distinguish these two issues (services + aiida) may remove a lot of confusion and I can try to implement that when I get to this (I plan to create a PR by the end of the week).

**Closed** 2020-11-06 16:23 UTC
Labels: priority/important, topic/documentation
