### ISSUE TITLE
Docs search returns invalid links

### ISSUE THREAD

**Issue by VictorEijkhout** [aiidateam/aiida-core#4368] opened 2020-09-10 15:08 UTC
Searching in readthedocs returns invalid links such as:

https://aiida-core.readthedocs.io/projects/aiida-core/en/latest/topics/schedulers.html?highlight=slurm

The first two or three components of that path should be omitted: the correct link is

https://aiida-core.readthedocs.io/en/latest/topics/schedulers.html#slurm

**Comment by sphuber** [comment] 2020-09-16 12:38
Thanks for the report @VictorEijkhout . I am not sure who is responsible for the generation of these links, whether this is Sphinx, ReadTheDocs or some problem in our configuration. @ltalirz do you have an idea. I typed a whole suspected cause below, blaming the sphinx search extension that was added at some point, but it was quickly removed in 216b4ec3e3a3ba88effc027104476d4de00b2d5c. Any ideas? I also cannot remember that this was always the case. I definitely remember the search having worked since the new docs.

~~I think this may be due to the new (experimental) search feature of ReadTheDocs that we recently added in 5f486e3370a30ba6a509ff1c8e95351c9dbd68a6. I am not sure how to debug this and to determine whose fault this is, but maybe we should file a bug report [on their Github](https://github.com/readthedocs/readthedocs-sphinx-search). @ltalirz do you know who is responsible for the generation of these links in the search results? Note that when you added this, the version was `0.1.0rc1` and currently they are at `0.1.0rc3` so these bugs are to be expected, but we may want to reconsider including this until bugs have resolved (if this package is responsible for this problem that is, but I remember having encountered problems with this before).~~

**Comment by ltalirz** [comment] 2020-09-16 13:21
I believe this has something to do with the aiida <> aiida-core relationship on readthedocs.org (we did not want someone else to register `aiida.readthedocs.org`, so we registered it as well).
At the moment, `aiida-core` is configured as a subproject of `aiida`, and I just noticed that when you head to aiida-core.readthedocs.io, you are actually redirected to https://aiida.readthedocs.io/projects/aiida-core/en/latest/.
As far as I could see, on the site with the aiida prefix, all links in the search work fine.

One *can*, however, end up at the aiida-core prefix via direct links, such as https://aiida-core.readthedocs.io/en/latest/topics/cli.html#topics-cli
If one then starts searching in the documentation, e.g. for "batch scheduler"https://aiida-core.readthedocs.io/en/latest/search.html?q=batch+scheduler, then one ends up in a broken link as reported by @VictorEijkhout 

The link
https://aiida-core.readthedocs.io/projects/aiida-core/en/latest/topics/schedulers.html?highlight=slurm
would be corrected by switching to the aiida prefix:
https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/schedulers.html?highlight=slurm

To further complicate things, we currently had set up a redirect for aiida.readthedocs.io to go to aiida-core.readthedocs.io (but only for /):
![image](https://user-images.githubusercontent.com/1053245/93342724-f5d8d100-f82f-11ea-8919-46ac0244064f.png)
(I believe this redirect did not actually affect any of this behavior; I've removed it for now just to be safe).

I.e., in conclusion, we may have discovered a bug where if one enters via a subproject-specific link, the search results on RTD can give broken links.
I'll open an issue for this.

**Comment by VictorEijkhout** [comment] 2020-09-16 13:36
"One can, however, end up at the aiida-core prefix via direct links"

For what it's worth, I found your article in Nature, which has a documentation link in the introduction. I followed that, then immediately used the search.

So you're probably stuck with many people coming in that way.

**Comment by ltalirz** [comment] 2020-09-16 13:39
Thanks @VictorEijkhout - there are certainly a number of such links around on the web, also including our tutorial materials etc. so we should definitely look into fixing it.
I've opened https://github.com/readthedocs/readthedocs.org/issues/7487

**Comment by ltalirz** [comment] 2020-10-09 16:23
I've unassigned Chris here for the moment, since there is nothing to be done on our side than to wait for RTD to introduce a fix.
I've just pinged them again.

**Comment by ramirezfranciscof** [comment] 2020-10-12 08:55
@ltalirz ok, thanks Leo! Yeah, I would anyways have someone assigned to keeping track of when it is ready to be actionable (not necessarily meaning they have to be constantly mindfull of this, but at least to know who do we need to ask about the status of this and knows where/how to check if a long time passes with no news). Would it be ok for you to assign yourself for this then, since you seem to have made the contact with the RTD people?

**Comment by ltalirz** [comment] 2020-10-12 11:55
fine!

**Comment by sphuber** [comment] 2021-01-27 10:03
Just for reference and in case it is an important other route how this breaks.

1. Navigate to `https://aiida-core.readthedocs.io/en/latest`
2. Search for a term
3. All links will start with `https://aiida-core.readthedocs.io/projects/aiida-core/en/latest` which are broken
4. 
Removing `projects/aiida-core` will make the link work.

**Comment by ramirezfranciscof** [comment] 2021-02-24 10:40
This should have been solve by the latest release of RTD ([fixed here](https://github.com/readthedocs/readthedocs.org/pull/7880)).

From what I could check, searches now work properly. Could any of you @sphuber @ltalirz quickly verify this and close the issue? Thanks!

**Comment by ltalirz** [comment] 2021-02-24 11:01
I confirm that the search results on https://aiida-core.readthedocs.io/en/latest/search.html?q=batch+scheduler now point to the mother project with links like https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/schedulers.html?highlight=batch%20scheduler  that are no longer broken.

Cheers!

**Closed by ltalirz** 2021-02-24 11:01 UTC
Labels: priority/important, topic/documentation, type/bug

**Comment by sphuber** [comment] 2021-02-24 11:12
Confirmed as well
