### ISSUE TITLE
new ASE version uses f-strings but is installed under python 3.5

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#4295] opened 2020-08-10 09:10 UTC
See CI failure https://github.com/aiidateam/aiida-core/runs/965898145?check_suite_focus=true#step:11:334

It looks like this is an issue of ASE itself - README says python3.6 or later, but pypi metadata includes 3.5.

**Comment by ltalirz** [comment] 2020-08-10 09:16
Opened issue https://gitlab.com/ase/ase/-/issues/718

**Comment by greschd** [comment] 2020-08-10 09:16
As far as I understand, the PyPI metadata (Trove classifiers) aren't taken into account when choosing which version to install at all. The correct way to declare this incompatibility would be a `python_requires` in `setup.py` - which ASE doesn't seem to be doing at all, see https://gitlab.com/ase/ase/-/blob/master/setup.py

Crucially, the `python_requires` needs to be set already one version _before_ the compatibility is dropped - i.e., only if there is a released version with `python_requires>=3.5` will it install that if the newest version has `>=3.6`.

**Comment by ltalirz** [comment] 2020-08-10 09:18
Thanks @greschd , linked in the issue

**Comment by csadorf** [comment] 2020-08-12 06:07
The issue is resolved by recent ase patch releases.

**Closed by csadorf** 2020-08-12 06:07 UTC
Labels: topic/dependencies, topics/dependencies/constraint, type/bug
