### ISSUE TITLE
sphinx suppresses build errors on RTD

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3604] opened 2019-12-04 19:23 UTC
When building documentation of AiiDA plugins on readthedocs.org, there is no AiiDA database, so - obviously - sphinx running on RTD cannot process code that forces it to instantiate ORM objects.

When you put a `orm.Int(1)` somewhere on the module level, you'll get an error message from sphinx [1] - we should perhaps work on making it more useful, but at least you have some indication on what & where the problem is.

However, when you put a `orm.Int(1)` as the default value of an input/output port in a workflow spec (see e.g. [here](https://github.com/yakutovicha/aiida-raspa/blob/develop/aiida_raspa/workchains/aiida_base_restart.py#L95-L98)), and then use the AiiDA sphinx extension to document it, the html output of the extension will lack certain content but no error or warning will be shown in the sphinx output (see https://github.com/lsmo-epfl/aiida-lsmo/issues/18).

This makes both the detection and the debugging of such issues really difficult, even more so as one workchain may be exposing inputs/outputs of other workchains from other packages.

There are two directions along which we could make progress here:
 1. We need to find a way to display helpful error messages for this
 2. When the `IN_RT_DOC_MODE` value is `True`, we could consider attempting a "graceful" failure of all database operations, so that even when you have `orm.Int(1)` on the module level, perhaps a warning would be printed but the documentation would still build.

I think 1. definitely seems like a good idea.
2. has the potential of saving plugin developers with "slightly dirty" plugins from having to rewrite everything just in order to have their docs on RTD, but one would need to see whether/how such a "hook" could work.

Mentioning @sphuber @giovannipizzi @greschd for info

[1] The exception raised by sphinx
```
WARNING: autodoc: failed to import module 'workchains.aiida_base_restart' from module 'aiida_raspa'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  role "aiida" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida-raspa/aiida_raspa/workchains/__init__.py", line 11, in <module>
    from .base import RaspaBaseWorkChain
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida-raspa/aiida_raspa/workchains/base.py", line 9, in <module>
    from aiida_raspa.workchains.aiida_base_restart import BaseRestartWorkChain
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida-raspa/aiida_raspa/workchains/aiida_base_restart.py", line 14, in <module>
    orm.Bool(False)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/nodes/data/base.py", line 46, in __init__
    super(BaseType, self).__init__(**kwargs)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/nodes/node.py", line 119, in __init__
    user = user.backend_entity if user else User.objects(backend).get_default()
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/users.py", line 69, in get_default
    self._default_user = self.get(email=email)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/entities.py", line 136, in get
    return res.one()[0]
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/querybuilder.py", line 2085, in one
    res = self.all()
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/querybuilder.py", line 2160, in all
    return list(self.iterall(batch_size=batch_size))
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/querybuilder.py", line 2117, in iterall
    for item in self._impl.iterall(query, batch_size, self._attrkeys_as_in_sql_result):
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/implementation/django/querybuilder.py", line 442, in iterall
    with transaction.atomic():
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/transaction.py", line 158, in __enter__
    if not connection.get_autocommit():
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/backends/base/base.py", line 385, in get_autocommit
    self.ensure_connection()
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  role "aiida" does not exist

```

**Comment by ltalirz** [comment] 2019-12-04 19:35
Looking at what `aiida-core` does, I realize that it actually configures an sqlite database on readthedocs.org: 
https://github.com/aiidateam/aiida-core/blob/d750d513f7adf5126d43a230c9fb378de02f0772/docs/rtd_settings.py#L66-L71

This is currently not part of the plugin cutter - of course we could suggest this for plugins as well...

**Comment by giovannipizzi** [comment] 2019-12-04 21:05
As discussed also in #2515, I think we should discourage using nodes as defaults, and have lambdas instead. I couldn't find the issue where we explained/discussed this, but anyway this is not a limitation in AiiDA, but a "feature" of python, where defaults are instantiated once at module import time and become global objects, reused between calls.

@sphuber is the use of lambdas as defaults already implemented in AiiDA?

**Comment by sphuber** [comment] 2019-12-04 21:16
@giovannipizzi yes lambda's are supported as I recently [implemented it in plumpy](https://github.com/aiidateam/plumpy/pull/133). I wrote PR #3466 to start emitting warnings when people do not use lambdas, but it is on hold because of discussion. Would probably be a good idea to add this to the discussion agenda for the coding week.

@ltalirz I do not think that snippet you found is actually doing something, as in I don't think that is causing a sqlite database to be created on the fly such that these problems do not occur on RTD for `aiida-core`. If we were to instantiate a node on the import level in `aiida-core` we would have the same problem

**Comment by greschd** [comment] 2019-12-04 22:14
Am I understanding it correctly that this

> 
> [1] The exception raised by sphinx
> 
> ```
> WARNING: autodoc: failed to import module 'workchains.aiida_base_restart' from module 'aiida_raspa'; the following exception was raised:
> Traceback (most recent call last):
>   File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
>     self.connect()
>   ...

is the warning you see from sphinx _on readthedocs_?

My best guess is that:
- RTD doesn't use the ``Makefile`` from the repo, but builds with custom commands
- Since the ``-nW`` (convert warnings to errors) is specified there, no error is triggered

In that case, we could add a ``.readthedocs.yml`` file to the cookiecutter, which specifies ``fail_on_warning``: https://docs.readthedocs.io/en/latest/config-file/v2.html#sphinx

I've had good experiences with that config format [in my own plugins](https://github.com/greschd/aiida-optimize/blob/develop/.readthedocs.yml) - it mostly replaces configuring RTD through the web interface.

**Comment by ltalirz** [comment] 2019-12-05 07:38
> Would probably be a good idea to add this to the discussion agenda for the coding week.

I agree, let's discuss this issue there.

> @ltalirz I do not think that snippet you found is actually doing something

I see. I'll check what happens when I remove it.

> do you know why sphinx is completely silent when it's a default value instead of at the module level?

I don't. My first thought was to look in the AiiDA sphinx extension (which I guess you have as well) but I didn't see any try/except that seemed to matter.

> Is it something in sphinx, something in aiida / plumpy, or something in the sphinx extension that catches the error?

I would guess it is sphinx, since from the point of view of the other packages (plumpy/aiida) there should be no difference whether sphinx discovers it at the module level or when "looking "deeper" inside the code.

**Comment by greschd** [comment] 2019-12-05 10:01
@ltalirz you mentioned over at https://github.com/lsmo-epfl/aiida-lsmo/issues/18 that you could reproduce this locally -- is it enough to make a clean install of the ``aiida-lsmo`` ``develop`` branch with ``export READTHEDOCS=True`` and invalid AiiDA config? Or is it now fixed and I need to install a specific commit?

I want to understand this better, will have a look at the coding week.

**Comment by ltalirz** [comment] 2019-12-05 10:23
@greschd I would recommend not to go with aiida-lsmo but rather to take some other package with a working documentation that uses the AiiDA sphinx extension and then introduce the problem by specifying a default value for an input port of the form `orm.Int(1)` (or similar).

To reproduce it locally, notify your `conf.py` that you are on readthedocs (for plugins using the plugin cutter `export READTHEDOCS='True'`) and make sure to point your AiiDA path to somewhere where it does not find a working profile (`export AIIDA_PATH=/tmp`).

Note: The code to be documented may need to be inside a package for the error message to be suppressed. When I modified the tests of the aiida sphinx extension in aiida-core (which use a file `demo_workchain.py` in the working directory), the error message was not suppressed.

**Comment by sphuber** [comment] 2019-12-06 19:24
I am a bit confused as to whether you actually see the stack trace you posted when you build your docs or not. In the build that produces the HTML with missing spec content, do you see that stacktrace in the logs? If not, where did you get it from.

**Comment by ltalirz** [comment] 2019-12-06 21:29
>  In the build that produces the HTML with missing spec content, do you see that stacktrace in the logs?

No, in that case there is nothing.

> If not, where did you get it from.

See above:

> When you put a orm.Int(1) somewhere on the module level, you'll get an error message from sphinx [1]

**Closed** 2019-12-12 18:37 UTC
Labels: topic/documentation, topic/processes, type/enhancement
