### ISSUE TITLE
Code style in sphinx documentation

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#3640] opened 2019-12-10 18:43 UTC
We need to decide, for consistency, the following:
- length of lines (and rule on where to split: after each sentence, after a given number of characters, ...) for the .rst documentation files
- rule on how to use the line defining headers `+++++`, `-------`, `=======` consistently and in which order (and how this interacts when subpages are imported)
- (maybe related to the one above) how to have consistent breadcrumbs. E.g. see [here](https://aiida-core.readthedocs.io/en/latest/working_with_aiida/tips/ssh_proxycommand.html), where the breadcrumb says `Docs » Getting started » Increasing the debug level » Using the proxy_command option with ssh` where it's using the first header of each file, while it should rather be `Working with AiiDA - Troubleshooting - Various Tips and tricks - Using the proxy_command option with ssh` (see e.g. the tree on the right).

**Comment by csadorf** [comment] 2019-12-11 16:58
As discussed with @ltalirz , I am going to add a style guide to the [wiki](https://github.com/aiidateam/aiida-core/wiki/Writing-documentation) which will define these things and ping you for review.

I further would like to remove the [Sphinx cheatsheet](https://aiida-core.readthedocs.io/en/latest/developer_guide/tools/sphinx_cheatsheet.html) from the `aiiida-core` documentation, because it 1. constitutes project (meta) and not software documentation and 2. to avoid any overlap/conflicts between this and the guidelines in the wiki.

**Comment by csadorf** [comment] 2019-12-12 06:51
@giovannipizzi I've extended the [wiki documentation](https://github.com/aiidateam/aiida-core/wiki/Writing-documentation) to include a [style guide](https://github.com/aiidateam/aiida-core/wiki/Writing-documentation#style-guide).

Concerning your last point about the correct breadcrumb hierarchy: As far as I can tell, this is largely caused by inconsistent section hierarchy and work-arounds to include sections at specific locations with otherwise only minimal modifications (as was previously demanded). I'm going to pay attention to this during my initial pass at restructuring and will update the wiki page to provide guidance on how to ensure consistency in that matter.

While I anticipate minor continuous updates to the wiki documentation, I'd like to consider this issue closed now.

**Comment by ltalirz** [comment] 2019-12-12 15:35
@giovannipizzi I agree - I think the style guide is reasonable and we can close this

**Comment by ltalirz** [comment] 2019-12-12 15:35
happy to reopen if you disagree

**Closed by ltalirz** 2019-12-12 15:35 UTC
Labels: priority/quality-of-life, topic/documentation, type/accepted feature
