### ISSUE TITLE
Return error code != 0 for errors during `verdi import`

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-core#4430] opened 2020-10-08 13:29 UTC
### Describe the bug

If a migration of an export archive fails, the return code is still `0`.

### Steps to reproduce

Use `verdi export migrate` with an invalid export archive.
Check return code in the terminal afterwards (`$ echo $?`).

### Expected behavior

For any reporting within `verdi`, if `ERROR:` is printed/returned, the return code should _not_ be `0`.

### Your environment

- Operating system: Ubuntu 18.04 LTS in WSL 2.0 on Windows 10.
- Python version: 3.7
- aiida-core version: 1.4.2

### Additional context

This was found by @asle85 during automatic migration of archives for Materials Cloud via Ansible playbooks.

**Comment by CasperWA** [comment] 2020-10-08 13:36
It seems there are two different functions for returning an error from `verdi`. One can either use `aiida.cmdline.utils.echo.echo_error` or `aiida.cmdline.utils.echo.echo_critical`. `echo_critical` _will_ exit with return code `1`, while `echo_error` will return with code `0`. Is this intended @ltalirz @giovannipizzi @sphuber?

**Comment by sphuber** [comment] 2020-10-08 13:44
This is the intended behavior yes. If the command should fail, one should use `echo_critical`. If you need to continue the command, you can use `echo_error` but than return non-zero exit value yourself.

**Comment by ltalirz** [comment] 2020-10-08 14:12
Closing this - feel free to ask further questions if anything is unclear

**Comment by CasperWA** [comment] 2020-10-08 14:14
I have repurposed this issue to return a non-zero error code in `verdi import` if an error occurs.

**Comment by ltalirz** [comment] 2020-10-29 17:27
@chrisjsewell After the refactoring, is `verdi import` now returning a non-zero exit code for all failures?

**Comment by chrisjsewell** [comment] 2020-10-29 18:10
Marking this as closed by #4532, and we can double-check that this is actually the case

**Closed** 2020-11-03 09:31 UTC
Labels: design-issue, priority/important, topic/export-import, topic/verdi, type/bug
