### ISSUE TITLE
Creating entities through verdi in a Jupyter notebook

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-core#4230] opened 2020-07-08 12:27 UTC
### Describe the current issue

If one creates an AiiDA entity using the verdi CLI in a Jupyter notebook (confused yet?), then the entity won't be reachable unless the Jupyter kernel is restarted.

### Describe the solution you'd like

We need to document that using `verdi` commands, such as `verdi code setup` run as `!verdi code setup` in a Jupyter notebook _requires_ a kernel restart.
In general, I would even go so far as recommending to only use `verdi` from a terminal, never within a notebook, but that's my take on it.

**Comment by sphuber** [comment] 2020-07-08 12:43
I am not convinced this is exactly the case. This came up during the tutorial, and I suspect the profile that `verdi` used simply was not the same that was loaded in the notebook. Launching `verdi` from a notebook using `!verdi` launches a separate Python interpreter and will use the profile that is the default at that time. If that differs from the profile that the notebook has loaded, of course the notebook won't be able to load it. If this is the scenario, it is not a bug but just a user mistake.

**Comment by sphuber** [comment] 2020-07-08 14:34
I think this issue can be closed. I just ran the following test in a jupyter notebook on `develop`:
```
!verdi code setup -L bash -D bash -P arithmetic.add --on-computer -Y localhost --remote-abs-path /bin/bash -n
from aiida import load_profile
load_profile()
from aiida.orm import load_code
load_code('bash@localhost')
```
and the code loaded just fine.

**Comment by sphuber** [comment] 2020-07-08 15:05
Pinging @chrisjsewell and @giovannipizzi for comment

**Comment by CasperWA** [comment] 2020-07-08 15:41
@sphuber Can the issue be related to changing default profile through `!verdi` in the notebook before doing the snippet you mentioned above?

**Comment by sphuber** [comment] 2020-07-08 15:48
yes, of course. I you run the notebook and load `profile_a`, but then you change the default profile to `profile_b` (be it through `!verdi` or even through the python API in the notebook), when you then execute any verdi command from the notebook, that will be executed for `profile_b`. Still I would say this is to be expected and not something we should guard against

**Comment by CasperWA** [comment] 2020-07-08 16:09
I'm simply trying to figure out why the code loading didn't work until the kernel was restarted in this notebook (issue from the tutorial).
I'll probably have to do some testing myself.

**Comment by sphuber** [comment] 2020-07-08 16:22
Sure, but I am almost a 100% certain that it was just due to mismatching profiles. What other test, besides the one I did, were you planning on doing? If you think there was something specific in that particular VM of the tutorial, there is no way to recreate that anyway without knowing what they did.

**Comment by chrisjsewell** [comment] 2020-07-08 16:23
> I'll probably have to do some testing myself.

yep I think first we need a reproducible failure, before as ruling notebooks entirely lol 😉 
still actually I do have issues with verdi commands that require input, in notebooks. I have a feeling though that this may have been fixed in newer notebook versions

**Comment by sphuber** [comment] 2020-07-08 16:27
> yep I think first we need a reproducible failure

Hold on though. This whole "issue" is based on the report of a user, without us knowing what they did exactly. For all we know, what really happened is as I described. Fine if you don't believe that, but how do you intend to prove a negative? If you try some more and you don't manage to reproduce, are we going to keep this open forever? Might as well try to disprove god...

**Comment by chrisjsewell** [comment] 2020-07-08 16:28
oh no I'm completely with you on this @sphuber lol, I'm saying if we can't reproduce the failure then the issue should not be open

**Comment by CasperWA** [comment] 2020-07-08 16:33
@sphuber : https://en.wikipedia.org/wiki/Existence_of_God#Ontological_argument ... Just saying 😂

**Comment by sphuber** [comment] 2020-07-08 16:37
> @sphuber : https://en.wikipedia.org/wiki/Existence_of_God#Ontological_argument ... Just saying joy

That is my point though, it reads:

> The argument proposes that God's existence is self-evident.

so, no point trying to disprove the Good Lord.

**Comment by chrisjsewell** [comment] 2020-07-08 16:41
>  https://en.wikipedia.org/wiki/Existence_of_God#Ontological_argument ... Just saying 😂

good point, do you want to open an issue on that 😆

**Closed** 2020-07-08 20:41 UTC
Labels: topic/documentation
