### ISSUE TITLE
Docs: 404

### ISSUE THREAD

**Issue by LuigiaCristiano** [aiidateam/aiida-core#5964] opened 2023-04-13 14:15 UTC
I cannot find the documentation for v2.2.2 by using the link available in the documentation of aiida previous version
(e.g. [v2.2.2](https://aiida.readthedocs.io/projects/aiida-core/en/v2.2.2/get_started/daemon.html))
my browser cannot access the linked web page

**Comment by sphuber** [comment] 2023-04-13 21:25
May I ask where you got the link from?

**Comment by LuigiaCristiano** [comment] 2023-04-14 13:04
Hi thanks for the quick reply,
I got the link from the following page of the documentation, 
https://aiida.readthedocs.io/projects/aiida-core/en/v1.0.0b1/get_started/daemon.html

**Comment by sphuber** [comment] 2023-04-14 14:32
I see, thanks for the report. This is due to the fact that the documentation changed completely in v2.0 and we didn't have the resources to add redirects for all the old links. Your best bet is to got to the home page of the latest documentation and start reading there.

This is also a duplicate of https://github.com/aiidateam/aiida-core/issues/5035 so I will close this and we continue discussion there.

**Closed by sphuber** 2023-04-14 14:32 UTC
Labels: topic/documentation
