### ISSUE TITLE
Processes can be paused without proxying it to the node

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#3694] opened 2019-12-20 09:09 UTC
I am running a VaspCalulation, the state is `Waiting` and the status show `Monitoring scheduler: job state QUEUED`. But when I gotocomputer to check the calculation the process is successfully finished.
It happened because the network problem. I also check the logs of the process:
```
...
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/socket.py", line 748, in getaddrinfo                   
 |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):                                          
 | socket.gaierror: [Errno -3] Temporary failure in name resolution
```

My aiida version is 1.0.1

**Comment by unkcpz** [comment] 2019-12-20 09:15
The full log report is:
```
+-> ERROR at 2019-12-20 01:55:33.919360+00:00                                                                   [26/370]
 | Traceback (most recent call last):                                                                                   
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/site-packages/aiida/engine/utils.py", line 176, in exponential_backoff_retry                                                                                                   
 |     result = yield coro()                                                                                            
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/site-packages/tornado/gen.py", line 1055, in run       
 |     value = future.result()                                                                                          
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/site-packages/tornado/concurrent.py", line 238, in result                                                                                                                      
 |     raise_exc_info(self._exc_info)                                                                                   
 |   File "<string>", line 4, in raise_exc_info                                                                         
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/site-packages/tornado/gen.py", line 1063, in run        |     yielded = self.gen.throw(*exc_info)                                                                              
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/site-packages/aiida/engine/processes/calcjobs/tasks.py"
, line 175, in do_update                                                                                                 |     job_info = yield cancellable.with_interrupt(update_request)                                                      
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/site-packages/tornado/gen.py", line 1055, in run       
 |     value = future.result()                                                                                          
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/site-packages/tornado/concurrent.py", line 238, in resu
lt                                                                                                                       |     raise_exc_info(self._exc_info)                                                                                   
 |   File "<string>", line 4, in raise_exc_info                                                                         
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/site-packages/tornado/gen.py", line 1063, in run       
 |     yielded = self.gen.throw(*exc_info)                                                                              
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/site-packages/aiida/engine/utils.py", line 93, in with_
interrupt                                                                                                               
 |     result = yield wait_iterator.next()  # pylint: disable=stop-iteration-return
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/site-packages/tornado/gen.py", line 1055, in run
 |     value = future.result() 
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/site-packages/tornado/concurrent.py", line 238, in resu
lt
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 4, in raise_exc_info
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/site-packages/aiida/engine/processes/calcjobs/manager.p
y", line 145, in _update_job_info
 |     self._jobs_cache = yield self._get_jobs_from_scheduler()
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/site-packages/tornado/gen.py", line 1055, in run
 |     value = future.result() 
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/site-packages/tornado/concurrent.py", line 238, in resu
lt
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 4, in raise_exc_info
|   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/site-packages/tornado/gen.py", line 1063, in run
 |     yielded = self.gen.throw(*exc_info)
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/site-packages/aiida/engine/processes/calcjobs/manager.p
y", line 101, in _get_jobs_from_scheduler
 |     transport = yield request
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/site-packages/tornado/gen.py", line 1055, in run
 |     value = future.result() 
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/site-packages/tornado/concurrent.py", line 238, in resu
lt
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 4, in raise_exc_info
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/site-packages/aiida/engine/transports.py", line 91, in 
do_open
 |     transport.open()
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/site-packages/aiida/transports/plugins/ssh.py", line 32
0, in open
 |     self._client.connect(self._machine, **connection_arguments)
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/site-packages/paramiko/client.py", line 340, in connect
 |     to_try = list(self._families_and_addresses(hostname, port))
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/site-packages/paramiko/client.py", line 204, in _famili
es_and_addresses
 |     hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM
 |   File "/home/unkcpz/miniconda3/envs/aiida-vasp/lib/python3.7/socket.py", line 748, in getaddrinfo
 |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
 | socket.gaierror: [Errno -3] Temporary failure in name resolution
```

**Comment by sphuber** [comment] 2019-12-20 14:10
Can you please load the node in a shell and print `node.paused` and see what it prints.
Can you do `verdi process play <id>`?
Have you tried to restart the daemon with `verdi daemon restart --reset`?

**Comment by unkcpz** [comment] 2019-12-21 00:32
`verdi daemon restart --reset` doesn't solve the problem.

`node.paused` printed `False`. 
`verdi process play <id>` says "Success: scheduled play Process<9807>" and the process start to run and problem solved.

I have to re-play all the process by hand? `verdi process play -a` not working in this situation.

**Comment by sphuber** [comment] 2019-12-23 09:04
Thanks for the report. It is true that in this case you had to do `verdi process play` manually because the `--all` flag only targets processes that are paused, and yours wasn't. At least the _node_ in the database wasn't, but in actuality the _process_ was paused. This is why it seemed stuck, but `verdi process list` did not list it as paused. This is the real bug and I think I have seen it before but I am not sure what causes it. When a process is paused it is the real process instance in memory that is paused and that causes the engine to stop running it temporarily. There is a hook that should then also set a paused attribute on the corresponding node such that when we do `verdi process list` the correct status is shown. Apparently there is a way where this paused attribute does not get properly set. I have adapted the issue title to reflect this and will keep this open to fix the bug

**Comment by unkcpz** [comment] 2019-12-24 03:01
Thanks. 
The bug only show up when I use AiiDA in an unstable network condition, so it may not easy to reproduce. But one thing for sure is that all my paused state is caused by exponential backoff mechanism. 
I will give more information about it when it appears again.

**Comment by zhubonan** [comment] 2020-06-06 10:14
Had similar issue here - a few of my `CalcJob` are not continuing, despite being marked as `playing`. Looking at the raw data inside the `checkpoints`, I found it has something like:

```
'_paused:\n'
 "  '!!meta':\n"
 '    class_name: plumpy.persistence:SavableFuture\n'
 '  _done: false\n'
 '  _result: null\n'
 '_pid: 56137\n'
 '_pre_paused_status: null\n'
 '_state:\n'
 "  '!!meta':\n"
 '    class_name: aiida.engine.processes.calcjobs.tasks:Waiting\n'
 '  data: update\n'
 '  in_state: true\n'
 '  msg: Waiting for scheduler update\n'
 "_status: 'Pausing after failed transport task: update_calculation failed 5 "
``` 

but it does not have the `paused` key in its attributes, so it is shown as *playing*.

Maybe this is an edge case. I suspect at some point I played the task (after knowing it has transport failed), and the paused key is removed, but the plumpy state did not change accordingly. I can see the action on `plumpy.Process` side takes places first. But it is possible that it missed the checkpoint?

https://github.com/aiidateam/aiida-core/blob/9fcb78a1100166a66d5d5560e6618d3e4f59b002/aiida/engine/processes/process.py#L408-L414

Perhaps we can make a command for discovering inconsistency by looking into the checkpoints?

**Comment by sphuber** [comment] 2020-06-06 10:37
We could also add a hook on `load_instance_state` to refresh the `paused` attribute based on the reconstructed process instance from the checkpoint. At least this will update the attributes when the database is restarted or the task is picked up from the queue

**Comment by zhubonan** [comment] 2020-06-07 14:07
@sphuber That sounds like a very reasonable check to add. 

As for the cause, I suspect it is because when `on_playing` is called there is no immediate saving of the checkpoint. So it will wait until the next checkpoint saving for the unpaused state to be recorded into the database. As you can see, `on_pause` does save the checkpoint:

https://github.com/aiidateam/aiida-core/blob/9fcb78a1100166a66d5d5560e6618d3e4f59b002/aiida/engine/processes/process.py#L396-L414

This explains why shutting down the daemon soon after issuing `verdi process play` will give rise the problem.

Hence, when the daemon starts next time, the checkpoint it reads from the database for the process would be in the *paused* state still. 

The easy fix is to add a call to `self._save_checkpoint()`:

```python
     @override 
     def on_playing(self): 
         """ 
         The Process was unpaused so remove the paused attribute on the process node 
         """ 
         super().on_playing()
         self._save_checkpoint()
         self.node.unpause() 
```

**Comment by sphuber** [comment] 2024-06-01 13:52
This should have been fixed by https://github.com/aiidateam/aiida-core/pull/6206

**Closed by sphuber** 2024-06-01 13:52 UTC
Labels: type/bug, priority/important, topic/engine, topic/processes
