### ISSUE TITLE
Deprecate the `Profile.repository_path` property

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#5513] opened 2022-05-04 07:30 UTC
This is split off from #5451 . The `Profile.repository_path` was historically used to give the absolute filepath to the file repository on the local file system. However, this is a property of the storage backend and not all backends will have this. So instead of being generic to all profiles, this should be a storage specific setting. The property should be deprecated and all its uses should get the necessary information from the `PsqlDosBackend` instead.

**Comment by chrisjsewell** [comment] 2022-05-04 12:01
this is a duplicate of #5353

**Closed** 2022-07-14 19:04 UTC
Labels: topic/repository, topic/config, priority/important, type/refactoring, topic/storage
