### ISSUE TITLE
Files in `local_copy_list` permanently stored in the repository

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#4414] opened 2020-09-30 08:33 UTC
### Describe the bug

When submitting a calculation with a local copy list, files are also stored in the repository permanently.

### Expected behavior

The goal of the local copy list is exactly to avoid that these files are stored, since (at least in current versions of AiiDA, might change in the future with the new disk-objectstore) they occupy space, and e.g. for pseudopotentials in a DFT calculation there is no need to repeat these files for each node.

### Steps to reproduce

I'm using AiiDA 1.4.0.

1. submit and AiiDA-quantumespresso calculation
2. Check the repository content, and you will find the pseudos in the `pseudos` subfolder.

### Additional context

I think this was introduced when implementing the `provenance_exclude_list`.

The `local_copy_list` now leverages it, and the files in the local_copy_list are added here:
https://github.com/aiidateam/aiida-core/blob/4544bc49a50c9aa3abebd2837efb5626958ee2b4/aiida/engine/daemon/execmanager.py#L201

And then here they are not added to the final repository:
https://github.com/aiidateam/aiida-core/blob/4544bc49a50c9aa3abebd2837efb5626958ee2b4/aiida/engine/daemon/execmanager.py#L277-L283

However, this seems not to be working.
I think the reason is that the files in the `local_copy_list` are specified by aiida-quantumespresso as `./pseudo/Co.upf` and then the function above checks instead `pseudo/Co.upf`.
However, I think what aiida-quantumespresso is doing is not invalid, and the execmanager of AiiDA should take care of properly normalising also the relative path provided in the local_copy_list.

**Comment by giovannipizzi** [comment] 2020-09-30 08:34
Pinging @sphuber as he implemented this, @espenfl as I think he's using the `provenance_exclude_list` in the VASP plugin to check if he's affected by this.

**Comment by sphuber** [comment] 2020-09-30 08:57
This is actually probably causes by `9dfad2efbe9603957a54d0123a3cec2ee48b54bd` which we implemented to fix a bug in the `local_copy_list`. The easiest solution to that particular solution was to copy the files of the `local_copy_list` to the sandbox folder and also add them to the `provenance_exclude_list`. This way, we could just simply copy the entire `folder` to the working directory and the `local_copy_list` files would _not_ be copied to the node's repository. I guess this doesn't actually work as intended then and was not noticed since apparently there is no simple test to guarantee that `local_copy_list` content does not end up in the node's repository. I will have a look now why

**Comment by sphuber** [comment] 2020-09-30 21:44
Fixed in #4415

**Closed by sphuber** 2020-09-30 21:44 UTC
Labels: priority/critical-blocking, topic/calc-jobs, topic/engine, topic/provenance, topic/repository, type/bug
