### ISSUE TITLE
Nightly tests failing

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#5812] opened 2022-12-02 10:52 UTC
Heya @sphuber as of 2 days ago the nightly tests are now failing.
Could you check this out, as obviously it may be due to one of your recent changes, cheers

**Comment by sphuber** [comment] 2022-12-02 12:31
First failure was https://github.com/aiidateam/aiida-core/actions/runs/3579359889 which was on 2022-11-30T17:03:55Z. The only two commits between that and the last successful run are:

* [Process: properly cleanup when exception in state transition](https://github.com/aiidateam/aiida-core/commit/a7be795a26aea9fdff1d6f762582f1b77801ff3d)
* [Bump jupyter-core from 4.9.1 to 4.11.2 in /requirements ](https://github.com/aiidateam/aiida-core/commit/ffe19dc8aa07eef503c46c9a58758f217d37e45b)

Seems the failures are not deterministic because this run just passed without issues: https://github.com/aiidateam/aiida-core/actions/runs/3601522571

But a manual trigger on `main` failed: https://github.com/aiidateam/aiida-core/actions/runs/3601596440/jobs/6067583436

So far, most failures have been in the Polish workchains, but the latter failed during the other workchains launched before that: https://github.com/aiidateam/aiida-core/actions/runs/3601596440/jobs/6067583436

It seems that the problem is with one of the outputs not being present. The updating of outputs was touched by a7be795a26aea9fdff1d6f762582f1b77801ff3d so that is a prime candidate for the problem.

**Comment by sphuber** [comment] 2022-12-02 19:24
The prime candidate commit [Process: properly cleanup when exception in state transition](https://github.com/aiidateam/aiida-core/commit/a7be795a26aea9fdff1d6f762582f1b77801ff3d) didn't change any significant in `aiida-core`, but it did update to `plumpy==0.21.1` which did have some changes in the process flow, notably:

* [Process: Fix incorrect overriding of transition_failed](https://github.com/aiidateam/plumpy/commit/720dfa05c9b7779a98e31ba602f77db27a70778a)
* [StateMachine: transition directly to excepted if transition failed](https://github.com/aiidateam/plumpy/commit/2b435f7f105e5a54b9a1b128242f455e60bb6702)

These commits seem as the only reasonable candidates for having introduced the regression. However, I created a branch that reverts both of them (https://github.com/aiidateam/plumpy/commits/fix/potentially-broken-process-flow) and ran a branch of `aiida-core` against this `plumpy` branch, but the tests still fail: https://github.com/sphuber/aiida-core/actions/runs/3604251173/jobs/6073723793

On top of this, I cannot reproduce the failure locally, so I am not sure how to further debug this. What seems to be happening is that a `WorkChain` will think a subprocess has finished and proceeds to the next step to fetch its result, but the output node does not exist, or at least the `node.outputs.some_output` raises an `AttributeError`.

**Comment by sphuber** [comment] 2022-12-02 21:22
Next step: comparing the installed Python libraries between the last successful run and the first failed run:

* [Last success](https://github.com/aiidateam/aiida-core/actions/runs/3570020210/jobs/6000584246)
* [First failure](https://github.com/aiidateam/aiida-core/actions/runs/3579359889/jobs/6033315862)

The diff in `pip freeze` output is:
```diff
--- /home/sph/code/aiida/env/dev/aiida-core/success.txt	Fri Dec  2 21:52:34 2022
+++ /home/sph/code/aiida/env/dev/aiida-core/failed.txt	Fri Dec  2 21:53:08 2022
@@ -61,10 +61,10 @@
 jupyter-cache==0.4.3
 jupyter-client==6.1.12
 jupyter-console==6.4.0
-jupyter-core==4.9.1
 jupyter-server==1.13.5
 jupyter-server-mathjax==0.2.6
 jupyter-sphinx==0.3.2
+jupyter_core==4.11.2
 jupyterlab-pygments==0.1.2
 jupyterlab-widgets==1.0.2
 kiwipy==0.7.5
```

Now this change was due to a commit that also falls within the window where the `nightly` started failing: [Bump jupyter-core from 4.9.1 to 4.11.2 in /requirements](https://github.com/aiidateam/aiida-core/commit/ffe19dc8aa07eef503c46c9a58758f217d37e45b)

I didn't originally consider this as a candidate, because it doesn't seem to be related to the bug at all. I created a branch off of `main` and reverted the commit that updated `jupyter-core` but the nightly still failed https://github.com/sphuber/aiida-core/actions/runs/3605032879/jobs/6075016651  So it seems not be responsible.

So we are back to thinking that `plumpy==0.21.1` is responsible. The last successful run was the first nightly build to run with that version. The fact that it passed may just have been luck though, since we have already shown that the failure is not deterministic.

**Comment by sphuber** [comment] 2022-12-03 13:59
Ok, I think I finally located the source of the issue. It seems that the change in order of the `update_outputs` and `node.set_process_state` is at fault. I don't fully understand why, but reverting this to the original order seems to fix the problem. I have prepared a branch that is essentially `main` but just reverts this order change (committed in [Process: properly cleanup when exception in state transition](https://github.com/aiidateam/aiida-core/commit/a7be795a26aea9fdff1d6f762582f1b77801ff3d)) and ran the nightly 4 times, and 4 times it passed (https://github.com/sphuber/aiida-core/actions/runs/3607922383).

So the solution I think is to restore the original order (calling `update_outputs` first) but wrapping it in try-except and re-raising, which allows to call `node.set_process_state` in the finally clause, guaranteeing that it is called, even if the `update_outputs` call excepts.

**Closed** 2022-12-05 15:42 UTC
Labels: type/bug
